export interface Hex {q:number;r:number}
export const HEX_DIRECTIONS:Hex[]=[{q:1,r:0},{q:1,r:-1},{q:0,r:-1},{q:-1,r:0},{q:-1,r:1},{q:0,r:1}];
export const hexKey=(h:Hex)=>`${h.q},${h.r}`;
export const hexDistance=(h:Hex)=>Math.max(Math.abs(h.q),Math.abs(h.r),Math.abs(h.q+h.r));
export const hexCells=(radius=5)=>Array.from({length:radius*2+1},(_,i)=>i-radius).flatMap(q=>Array.from({length:radius*2+1},(_,i)=>i-radius).map(r=>({q,r}))).filter(h=>hexDistance(h)<=radius);
export function escapePath(start:Hex,obstacles:Hex[],radius=5):Hex[]|null {const blocked=new Set(obstacles.map(hexKey)),queue=[start],parents=new Map<string,Hex|null>([[hexKey(start),null]]);for(let i=0;i<queue.length;i++){const p=queue[i];if(hexDistance(p)===radius){const path:Hex[]=[];let at:Hex|null=p;while(at){path.unshift(at);at=parents.get(hexKey(at))??null;}return path;}for(const d of HEX_DIRECTIONS){const n={q:p.q+d.q,r:p.r+d.r},k=hexKey(n);if(hexDistance(n)<=radius&&!blocked.has(k)&&!parents.has(k)){parents.set(k,p);queue.push(n);}}}return null;}
export interface TrapBoard {position:Hex;obstacles:Hex[];countdown:number;breakUsed:boolean;radius:number}
export function previewTrap(board:TrapBoard,placed:Hex){const obstacles=[...board.obstacles,placed],dance=board.countdown===1,path=escapePath(board.position,obstacles,board.radius);if(path)return {outcome:hexDistance(path[1]??board.position)===board.radius?'escape' as const:'move' as const,position:path[1]??board.position,obstacles,dance,breakUsed:board.breakUsed};if(dance&&!board.breakUsed){const blocked=new Set(obstacles.map(hexKey)),choices=HEX_DIRECTIONS.map(d=>({q:board.position.q+d.q,r:board.position.r+d.r})).filter(h=>blocked.has(hexKey(h)));const scored=choices.map((h,index)=>({h,index,path:escapePath(h,obstacles.filter(o=>hexKey(o)!==hexKey(h)),board.radius)})).sort((a,b)=>(a.path?0:1)-(b.path?0:1)||(a.path&&b.path?a.path.length-b.path.length:(board.radius-hexDistance(a.h))-(board.radius-hexDistance(b.h)))||a.index-b.index);if(scored.length){const position=scored[0].h;return {outcome:hexDistance(position)===board.radius?'escape' as const:'break' as const,position,obstacles:obstacles.filter(o=>hexKey(o)!==hexKey(position)),dance,breakUsed:true};}}
 return {outcome:'capture' as const,position:board.position,obstacles,dance,breakUsed:board.breakUsed};}
