import {adventureDeck,handTotal,legalTrades,type AdventureCard,type ExpeditionPlayer} from '@/lib/greed';
import {shuffleWith,choose,type BatchModule,type BatchState,type BatchContext,turn,nextRound,finish,point} from './core';
interface Data {deck:AdventureCard[];discard:AdventureCard[];players:Record<string,ExpeditionPlayer>;roundStart:Record<string,number>;history:{playerId:string;text:string;card?:AdventureCard}[];last:{playerId:string;card:AdventureCard;duplicate?:number;result:string}|null;peek:AdventureCard|null;passes:string[];queue:{id:string;card?:AdventureCard}[];actor:string}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext){const actor=g.participants[(g.round-1)%g.participants.length];g.data={deck:shuffleWith(adventureDeck(),c.random),discard:[],players:Object.fromEntries(g.participants.map(id=>[id,{hand:[],shield:false,status:'active',banked:0}])),roundStart:{...g.points},history:[],last:null,peek:null,passes:[],queue:[],actor} satisfies Data;g.phase='turn';turn(g,actor,c.now+c.ms.wallTurn);}
function end(g:BatchState,c:BatchContext){const d=data(g);for(const [id,p] of Object.entries(d.players))if(p.status!=='bust'){p.banked=handTotal(p.hand);point(g,id,p.banked);}g.completedRounds++;g.phase='roundResult';turn(g,null,c.now+c.ms.feedback*3);}
function after(g:BatchState,c:BatchContext){const d=data(g);d.peek=null;const alive=g.participants.filter(id=>d.players[id].status!=='bust');if(!d.deck.length||!alive.length||alive.every(id=>d.passes.includes(id))){end(g,c);return;}const start=g.participants.indexOf(d.actor),next=Array.from({length:g.participants.length},(_,i)=>g.participants[(start+i+1)%g.participants.length]).find(id=>alive.includes(id))!;d.players[next].status='active';d.actor=next;g.phase='turn';turn(g,next,c.now+c.ms.wallTurn);}
function log(g:BatchState,id:string,text:string,card?:AdventureCard){data(g).history.push({playerId:id,text,card});}
function number(g:BatchState,id:string,card:number){const d=data(g),p=d.players[id];let result='';if(p.hand.includes(card)){d.discard.push(card);if(p.shield){p.shield=false;result='护盾抵消重复';}else{d.discard.push(...p.hand);p.hand=[];p.status='bust';result='重复数字，爆点归零';}}else{p.hand.push(card);result=`临时分 ${handTotal(p.hand)}`;}d.last={playerId:id,card,duplicate:result.includes('重复')?card:undefined,result};log(g,id,result,card);}
function drain(g:BatchState,c:BatchContext){const d=data(g);while(d.queue.length){const task=d.queue.shift()!,p=d.players[task.id];if(p.status==='bust')continue;const card=task.card??d.deck.shift();if(card===undefined)continue;d.passes=[];d.last={playerId:task.id,card,result:'抽牌'};if(typeof card==='number'){number(g,task.id,card);continue;}d.discard.push(card);
 if(card==='shield'){p.shield=true;log(g,task.id,'获得护盾（最多一层）',card);}
 else if(card==='peek'&&d.deck.length){d.peek=d.deck[0];log(g,task.id,'查看下一张牌，等待私人选择',card);g.phase='peek';turn(g,task.id,c.now+c.ms.turn);return;}
 else if(card==='trick'&&legalTrades(d.players,task.id).length){log(g,task.id,'选择合法数字交换',card);g.phase='trick';turn(g,task.id,c.now+c.ms.turn);return;}
 else if(card==='delivery'){const start=g.participants.indexOf(task.id);const tasks=Array.from({length:g.participants.length},(_,i)=>({id:g.participants[(start+i+1)%g.participants.length]})).filter(t=>d.players[t.id].status!=='bust');d.queue.unshift(...tasks);log(g,task.id,'信使鸟：从下一位开始依次补牌，最后自己补牌',card);}
 else if(card==='discard'){for(const id of g.participants){const target=d.players[id];if(id===task.id||target.status==='bust'||!target.hand.length)continue;const at=Math.floor(c.random()*target.hand.length),lost=target.hand.splice(at,1)[0];d.discard.push(lost);log(g,id,`猾大狐使你弃掉 ${lost}`,lost);}log(g,task.id,'猾大狐：其他玩家各随机弃一张数字牌',card);}
 else if(card==='double'){d.queue.unshift({id:task.id,card:4},{id:task.id,card:7});log(g,task.id,'弃世猴：依次获得 4 和 7',card);}
 else log(g,task.id,'特殊卡无可执行效果',card);
 }after(g,c);}
function stop(g:BatchState,id:string,c:BatchContext){const d=data(g);d.players[id].status='stopped';if(!d.passes.includes(id))d.passes.push(id);log(g,id,'暂时停手，本次不抽；下次仍可返场');if(d.queue.length)drain(g,c);else after(g,c);}
function trade(g:BatchState,id:string,option:ReturnType<typeof legalTrades>[number],c:BatchContext){const d=data(g),mine=d.players[id],other=d.players[option.target];mine.hand=mine.hand.filter(n=>n!==option.own).concat(option.other);other.hand=other.hand.filter(n=>n!==option.other).concat(option.own);log(g,id,`与 ${option.target} 交换 ${option.own} ↔ ${option.other}`);drain(g,c);}
export const pushYourLuck:BatchModule={
 create(g,c){g.totalRounds=c.settings.luckRounds;begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.currentPlayerId!==id||d.players[id]?.status==='bust')return '当前不能行动';if(g.phase==='turn'){if(a.type==='draw'){d.passes=[];d.queue.push({id});drain(g,c);return null;}if(a.type==='stop'){stop(g,id,c);return null;}}else if(g.phase==='peek'){if(a.type==='take-peek'){d.peek=null;d.queue.unshift({id});drain(g,c);return null;}if(a.type==='stop'){d.peek=null;stop(g,id,c);return null;}}else if(g.phase==='trick'&&a.type==='trade'){const option=legalTrades(d.players,id).find(t=>t.target===a.target&&t.own===a.own&&t.other===a.other);if(!option)return '交换会产生重复数字或目标已爆点';trade(g,id,option,c);return null;}return '请完成当前阶段操作';},
 advance(g,c){if(g.deadline===null||c.now<g.deadline)return;if(g.phase==='roundResult'){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}return;}if(['turn','peek'].includes(g.phase))stop(g,g.currentPlayerId!,c);else if(g.phase==='trick'){const options=legalTrades(data(g).players,g.currentPlayerId!);if(options.length)trade(g,g.currentPlayerId!,choose(options,c.random),c);else drain(g,c);}},
 snapshot(g,id){const d=data(g);return {players:structuredClone(d.players),remaining:d.deck.length,deckSize:adventureDeck().length,passes:[...d.passes],discard:[...d.discard],history:d.history.map(h=>({...h})),last:d.last?{...d.last}:null,peek:g.phase==='peek'&&g.currentPlayerId===id?d.peek:null,tradeOptions:g.phase==='trick'&&g.currentPlayerId===id?legalTrades(d.players,id):[]};},
 active(g){return Object.entries(data(g).players).filter(([,p])=>p.status!=='bust').map(([id])=>id);},abort(g){g.points={...data(g).roundStart};},
};
