import {adventureDeck,handTotal,legalTrades,type AdventureCard,type ExpeditionPlayer} from '@/lib/greed';
import {shuffleWith,choose,type BatchModule,type BatchState,type BatchContext,turn,nextRound,finish,point} from './core';
interface Data {deck:AdventureCard[];discard:AdventureCard[];players:Record<string,ExpeditionPlayer>;roundStart:Record<string,number>;history:{playerId:string;text:string;card?:AdventureCard}[];last:{playerId:string;card:AdventureCard;duplicate?:number;result:string}|null;peek:AdventureCard|null}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext){g.data={deck:shuffleWith(adventureDeck(),c.random),discard:[],players:Object.fromEntries(g.participants.map(id=>[id,{hand:[],shield:false,status:'active',banked:0}])),roundStart:{...g.points},history:[],last:null,peek:null} satisfies Data;g.phase='turn';turn(g,g.participants[(g.round-1)%g.participants.length],c.now+c.ms.wallTurn);}
function stop(g:BatchState,id:string){const p=data(g).players[id];p.status='stopped';p.banked=handTotal(p.hand);point(g,id,p.banked);data(g).history.push({playerId:id,text:`停手存入 ${p.banked} 分`});}
function after(g:BatchState,c:BatchContext){const d=data(g);d.peek=null;if(!d.deck.length)for(const [id,p] of Object.entries(d.players))if(p.status==='active')stop(g,id);const active=g.participants.filter(id=>d.players[id].status==='active');if(!active.length){g.completedRounds++;g.phase='roundResult';turn(g,null,c.now+c.ms.feedback*3);return;}const start=g.participants.indexOf(g.currentPlayerId!);const next=Array.from({length:g.participants.length},(_,i)=>g.participants[(start+i+1)%g.participants.length]).find(id=>active.includes(id))!;g.phase='turn';turn(g,next,c.now+c.ms.wallTurn);}
function draw(g:BatchState,c:BatchContext){const d=data(g),id=g.currentPlayerId!,p=d.players[id],card=d.deck.shift();if(card===undefined){after(g,c);return;}d.last={playerId:id,card,result:'抽牌'};
 if(typeof card==='number'){if(p.hand.includes(card)){d.discard.push(card);d.last.duplicate=card;if(p.shield){p.shield=false;d.last.result='护盾抵消重复，继续探险';}else{d.discard.push(...p.hand);p.hand=[];p.status='bust';d.last.result='重复数字，爆点归零';}}else{p.hand.push(card);d.last.result=`临时分 ${handTotal(p.hand)}`;}d.history.push({playerId:id,text:d.last.result,card});after(g,c);return;}
 d.discard.push(card);if(card==='shield'){p.shield=true;d.last.result='获得护盾（最多一层）';d.history.push({playerId:id,text:d.last.result,card});after(g,c);}else if(card==='peek'&&d.deck.length){d.peek=d.deck[0];d.history.push({playerId:id,text:'查看下一张牌，等待私人选择',card});g.phase='peek';turn(g,id,c.now+c.ms.turn);}else if(card==='trick'&&legalTrades(d.players,id).length){d.history.push({playerId:id,text:'选择合法数字牌交换',card});g.phase='trick';turn(g,id,c.now+c.ms.turn);}else{d.history.push({playerId:id,text:'特殊卡没有可执行效果',card});after(g,c);}}
function trade(g:BatchState,option:ReturnType<typeof legalTrades>[number],c:BatchContext){const d=data(g),id=g.currentPlayerId!,mine=d.players[id],other=d.players[option.target];mine.hand=mine.hand.filter(n=>n!==option.own).concat(option.other);other.hand=other.hand.filter(n=>n!==option.other).concat(option.own);d.history.push({playerId:id,text:`与 ${option.target} 交换 ${option.own} ↔ ${option.other}`});after(g,c);}
export const pushYourLuck:BatchModule={
 create(g,c){g.totalRounds=c.settings.luckRounds;begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.currentPlayerId!==id||d.players[id]?.status!=='active')return '当前不能行动';if(g.phase==='turn'){if(a.type==='draw'){draw(g,c);return null;}if(a.type==='stop'){stop(g,id);after(g,c);return null;}}else if(g.phase==='peek'){if(a.type==='take-peek'){draw(g,c);return null;}if(a.type==='stop'){stop(g,id);after(g,c);return null;}}else if(g.phase==='trick'&&a.type==='trade'){const option=legalTrades(d.players,id).find(p=>p.target===a.target&&p.own===a.own&&p.other===a.other);if(!option)return '交换会产生重复数字，或目标已经退出';trade(g,option,c);return null;}return '请完成当前阶段的操作';},
 advance(g,c){if(g.deadline===null||c.now<g.deadline)return;if(g.phase==='roundResult'){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}return;}if(['turn','peek'].includes(g.phase)){stop(g,g.currentPlayerId!);after(g,c);}else if(g.phase==='trick'){const options=legalTrades(data(g).players,g.currentPlayerId!);if(options.length)trade(g,choose(options,c.random),c);else after(g,c);}},
 snapshot(g,id){const d=data(g);return {players:structuredClone(d.players),remaining:d.deck.length,discard:[...d.discard],history:d.history.map(h=>({...h})),last:d.last,peek:g.phase==='peek'&&g.currentPlayerId===id?d.peek:null,tradeOptions:g.phase==='trick'&&g.currentPlayerId===id?legalTrades(d.players,id):[]};},
 active(g){return Object.entries(data(g).players).filter(([,p])=>p.status==='active').map(([id])=>id);},
 abort(g){g.points={...data(g).roundStart};},
};
