import {ALL_POKEMON,getPokemon} from '../pokedex';
import {choose,shuffleWith,type BatchModule,type BatchState,type BatchContext,turn,nextRound,finish} from './core';
export const AUCTION={startingCash:10000,targetCash:15000,maxBoxes:15,noSaleLimit:3,tools:{wide:100,focus:150,detector:100,scan:50}} as const;
export function cardValue(id:number){const p=getPokemon(id)!;const bst=p.hp+p.attack+p.defense+p.spAttack+p.spDefense+p.speed;return Math.round(100*2**((bst-300)/100));}
export function makeBox(random:()=>number):(number|null)[]{const size=8+Math.floor(random()*8);const cards=Array.from({length:size},()=>choose(ALL_POKEMON,random).id);return shuffleWith([...cards,...Array(25-size).fill(null)],random);}
export function auctionWinner(bids:Record<string,number>,round:number,random:()=>number):string|null {const positive=Object.entries(bids).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);if(!positive.length)return null;if(positive.length===1)return positive[0][0];const highest=positive[0][1],second=positive[1][1],tied=positive.filter(([,v])=>v===highest);if(round===3)return choose(tied,random)[0];if(tied.length>1)return null;return highest*(round===1?2:5)>=second*(round===1?3:6)?positive[0][0]:null;}
interface Info {tool:string;text:string;index?:number;pokemonId?:number|null;value?:number}
interface Data {box:(number|null)[];boxStart:Record<string,number>;tools:Record<string,Info[]>;fees:Record<string,number>;ready:string[];bids:Record<string,number>;bidRound:number;lastBids:{highest:number;second:number;ratio:number}|null;noSales:number;result:{cards:(number|null)[];prices:number[];value:number;buyer:string|null;bid:number;tradeProfit:number;fees:Record<string,number>;net:Record<string,number>;bids:Record<string,number>}|null}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext,noSales=0){g.data={box:makeBox(c.random),boxStart:{...g.points},tools:Object.fromEntries(g.participants.map(id=>[id,[]])),fees:Object.fromEntries(g.participants.map(id=>[id,0])),ready:[],bids:{},bidRound:1,lastBids:null,noSales,result:null} satisfies Data;g.phase='shop';turn(g,null,c.now+c.ms.turn*3);}
function bidding(g:BatchState,c:BatchContext){g.phase='bid';data(g).bids={};turn(g,null,c.now+c.ms.wallTurn);}
function settleBox(g:BatchState,c:BatchContext,buyer:string|null){const d=data(g),prices=d.box.map(id=>id===null?0:cardValue(id)),value=prices.reduce((a,b)=>a+b,0),bid=buyer?d.bids[buyer]:0;if(buyer)g.points[buyer]+=value-bid;d.noSales=buyer?0:d.noSales+1;d.result={cards:[...d.box],prices,value,buyer,bid,tradeProfit:buyer?value-bid:0,fees:{...d.fees},net:Object.fromEntries(g.participants.map(id=>[id,g.points[id]-d.boxStart[id]])),bids:{...d.bids}};g.completedRounds++;g.phase='boxResult';turn(g,null,c.now+c.ms.feedback*3);}
function decide(g:BatchState,c:BatchContext){const d=data(g);for(const id of g.participants)d.bids[id]??=0;const winner=auctionWinner(d.bids,d.bidRound,c.random);if(winner||d.bidRound===3){settleBox(g,c,winner);return;}const sorted=Object.values(d.bids).sort((a,b)=>b-a);d.lastBids={highest:sorted[0]??0,second:sorted[1]??0,ratio:d.bidRound===1?1.5:1.2};d.bidRound++;bidding(g,c);}
export const pokemonAuction:BatchModule={
 create(g,c){g.totalRounds=c.settings.auctionBoxes;g.points=Object.fromEntries(g.participants.map(id=>[id,AUCTION.startingCash]));begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.phase==='shop'){if(d.ready.includes(id))return '准备后不能再采购';if(a.type==='ready'){d.ready.push(id);if(c.online.every(p=>d.ready.includes(p)))bidding(g,c);return null;}const tool=a.tool as keyof typeof AUCTION.tools;if(a.type!=='buy-tool'||!Object.hasOwn(AUCTION.tools,tool))return '请选择道具';if(d.tools[id].length>=2)return '每箱最多购买两件';const cost=AUCTION.tools[tool];if(g.points[id]<cost)return '余额不足';let info:Info;
 if(tool==='wide'){if(!['row','column'].includes(a.axis as string)||!Number.isInteger(a.index)||Number(a.index)<0||Number(a.index)>4)return '请选择合法行或列';const index=a.index as number,values=d.box.filter((_,i)=>a.axis==='row'?Math.floor(i/5)===index:i%5===index).map(p=>p===null?0:cardValue(p));info={tool,text:`${a.axis==='row'?'行':'列'} ${index+1} 平均价值 ${(values.reduce((x,y)=>x+y,0)/5).toFixed(1)}`};}
 else if(tool==='focus')info={tool,text:`最高单卡 ${Math.max(...d.box.map(p=>p===null?0:cardValue(p)))}`};
 else if(tool==='detector')info={tool,text:`实际卡牌 ${d.box.filter(p=>p!==null).length} 张`};
 else{if(!Number.isInteger(a.index)||Number(a.index)<0||Number(a.index)>=25)return '请选择合法格子';const index=a.index as number,p=d.box[index],value=p===null?0:cardValue(p);info={tool,index,pokemonId:p,value,text:`第 ${index+1} 格：${p===null?'空':getPokemon(p)!.nameZh+'，价值 '+value}`};}
 g.points[id]-=cost;d.fees[id]+=cost;d.tools[id].push(info);return null;}
 if(g.phase!=='bid'||a.type!=='bid')return '当前不能报价';if(d.bids[id]!==undefined)return '本轮报价已锁定';if(!Number.isSafeInteger(a.amount)||Number(a.amount)<0||Number(a.amount)>g.points[id])return '报价须为不超过余额的非负整数';d.bids[id]=a.amount as number;if(c.online.every(p=>d.bids[p]!==undefined))decide(g,c);return null;},
 advance(g,c){if(g.deadline===null||c.now<g.deadline)return;if(g.phase==='shop')bidding(g,c);else if(g.phase==='bid')decide(g,c);else if(g.phase==='boxResult'){const d=data(g);if(Object.values(g.points).some(v=>v>=AUCTION.targetCash)||g.round>=g.totalRounds||d.noSales>=AUCTION.noSaleLimit||Object.values(g.points).every(v=>v===0))finish(g);else{nextRound(g);begin(g,c,d.noSales);}}},
 snapshot(g,id){const d=data(g);return {myCash:g.points[id]??0,myTools:d.tools[id]??[],myFees:d.fees[id]??0,ready:[...d.ready],myBid:d.bids[id]??null,bidRound:d.bidRound,submittedCount:Object.keys(d.bids).length,lastBids:d.lastBids,noSales:d.noSales,result:d.result,parameters:AUCTION};},
 publicPoints(g,id){const d=data(g);return ['boxResult','final'].includes(g.phase)?{...g.points}:{...d.boxStart,...(g.participants.includes(id)?{[id]:g.points[id]}:{})};},
 abort(g){g.points={...data(g).boxStart};},
};
