import {type BatchModule,type BatchState,type BatchContext,choose,turn,nextRound,finish,point} from './core';
export const DICE_IDS=[172,25,26,151,150,132];
export function legalCall(next:{count:number;face:number},previous:{count:number;face:number}|null,total:number){return Number.isInteger(next.count)&&next.count>=1&&next.count<=total&&Number.isInteger(next.face)&&next.face>=0&&next.face<5&&(!previous||next.count>previous.count||next.count===previous.count&&next.face>previous.face);}
export function countDice(dice:Record<string,number[]>,face:number){return Object.values(dice).flat().filter(n=>n===face||n===5).length;}
interface Data {lives:Record<string,number>;dice:Record<string,number[]>;alive:string[];eliminated:string[];call:{playerId:string;count:number;face:number}|null;history:{playerId:string;count:number;face:number}[];hand:number;result:{dice:Record<string,number[]>;call:Data['call'];actual:number;loser:string;challenger:string;holds:boolean;ordinary:number;wild:number;livesBefore:Record<string,number>;livesAfter:Record<string,number>}|null;results:NonNullable<Data['result']>[];next:string;ranking:string[]|null}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext){g.data={lives:Object.fromEntries(g.participants.map(id=>[id,3])),dice:{},alive:[...g.participants],eliminated:[],call:null,history:[],hand:0,result:null,next:choose(g.participants,c.random),ranking:null,results:[]} satisfies Data;roll(g,c);}
function roll(g:BatchState,c:BatchContext){const d=data(g);d.hand++;d.dice=Object.fromEntries(d.alive.map(id=>[id,Array.from({length:5},()=>Math.floor(c.random()*6))]));d.call=null;d.history=[];d.result=null;g.phase='turn';turn(g,d.next,c.now+c.ms.wallTurn);}
function open(g:BatchState,id:string,c:BatchContext){const d=data(g),call=d.call!;const actual=countDice(d.dice,call.face),holds=actual>=call.count,loser=holds?id:call.playerId;const livesBefore={...d.lives};d.lives[loser]--;d.result={dice:structuredClone(d.dice),call:{...call},actual,loser,challenger:id,holds,ordinary:Object.values(d.dice).flat().filter(n=>n===call.face).length,wild:Object.values(d.dice).flat().filter(n=>n===5).length,livesBefore,livesAfter:{...d.lives}};d.results.push(structuredClone(d.result));if(d.lives[loser]===0){d.eliminated.push(loser);d.alive=d.alive.filter(p=>p!==loser);const index=g.participants.indexOf(loser);d.next=Array.from({length:g.participants.length},(_,i)=>g.participants[(index+i+1)%g.participants.length]).find(p=>d.alive.includes(p))!;}else d.next=loser;
 if(d.alive.length===1){d.ranking=[d.alive[0],...d.eliminated.slice().reverse()];d.ranking.forEach((p,i)=>point(g,p,g.participants.length-i-1));g.completedRounds++;g.phase='roundResult';}else g.phase='open';turn(g,null,c.now+Math.max(c.ms.feedback*2,c.ms.feedback/1500*8000));
}
export const liarsDice:BatchModule={
 create(g,c){g.totalRounds=c.settings.diceMatches;begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.phase!=='turn'||g.currentPlayerId!==id||!d.alive.includes(id))return '当前不能叫数';if(a.type==='open'){if(!d.call)return '还没有叫数';const expected=a.expectedCall as Data['call'];if(a.expectedHand!==d.hand||!expected||expected.playerId!==d.call.playerId||expected.count!==d.call.count||expected.face!==d.call.face)return '叫数已更新，请核对最新叫数后再质疑';open(g,id,c);return null;}if(a.type!=='call'||!legalCall({count:a.count as number,face:a.face as number},d.call,d.alive.length*5))return '叫数必须增大，且不能超过当前骰子总数';d.call={playerId:id,count:a.count as number,face:a.face as number};d.history.push({...d.call});const next=d.alive[(d.alive.indexOf(id)+1)%d.alive.length];turn(g,next,c.now+c.ms.wallTurn);return null;},
 advance(g,c){if(g.phase==='final'||g.deadline===null||c.now<g.deadline)return;if(g.phase==='turn'){const d=data(g),id=g.currentPlayerId!;if(d.call)open(g,id,c);else this.action(g,id,{type:'call',count:1,face:0},c);}else if(g.phase==='open')roll(g,c);else if(g.phase==='roundResult'){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}}},
 snapshot(g,id){const d=data(g);return {results:structuredClone(d.results),lives:{...d.lives},alive:[...d.alive],myDice:d.dice[id]&&d.alive.includes(id)?[...d.dice[id]]:[],call:d.call?{...d.call}:null,history:d.history.map(h=>({...h})),hand:d.hand,totalDice:d.alive.length*5,result:d.result?structuredClone(d.result):null,ranking:d.ranking?[...d.ranking]:null};},
 active(g){return data(g).alive;},
};
