import {hexCells,hexDistance,hexKey,escapePath,previewTrap,type TrapBoard,type Hex} from '@/lib/meloetta';
import {shuffleWith,nextOnline,type BatchModule,type BatchState,type BatchContext,turn,nextRound,finish,point} from './core';
interface Data extends TrapBoard {last:{playerId:string;placed:Hex;outcome:string;dance:boolean}|null;timeouts:number}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext){let obstacles:Hex[]=[];for(let attempt=0;attempt<100;attempt++){obstacles=shuffleWith(hexCells().filter(h=>hexDistance(h)>0),c.random).slice(0,8);if(escapePath({q:0,r:0},obstacles))break;}if(!escapePath({q:0,r:0},obstacles))obstacles=hexCells().filter(h=>hexDistance(h)===5&&h.q<0).slice(0,8);g.data={position:{q:0,r:0},obstacles,countdown:2+Math.floor(c.random()*3),breakUsed:false,radius:5,last:null,timeouts:0} satisfies Data;g.phase='turn';turn(g,g.participants[(g.round-1)%g.participants.length],c.now+c.ms.wallTurn);}
export const surroundMeloetta:BatchModule={
 create(g,c){g.totalRounds=c.settings.trapRounds;begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.phase==='idle'&&a.type==='resume'){d.timeouts=0;g.notice=null;g.phase='turn';turn(g,id,c.now+c.ms.wallTurn);return null;}if(g.phase!=='turn'||g.currentPlayerId!==id)return '还没轮到你';const placed={q:a.q as number,r:a.r as number};if(a.type!=='block'||!Number.isInteger(placed.q)||!Number.isInteger(placed.r)||hexDistance(placed)>d.radius||hexKey(placed)===hexKey(d.position)||d.obstacles.some(h=>hexKey(h)===hexKey(placed)))return '请选择合法空格';const result=previewTrap(d,placed);d.position=result.position;d.obstacles=result.obstacles;d.breakUsed=result.breakUsed;d.countdown=result.dance?2+Math.floor(c.random()*3):d.countdown-1;d.last={playerId:id,placed,outcome:result.outcome,dance:result.dance};d.timeouts=0;if(['capture','escape'].includes(result.outcome)){if(result.outcome==='capture')point(g,id,3);g.completedRounds++;g.phase='roundResult';turn(g,null,c.now+c.ms.feedback*3);}else{g.phase='movement';g.deadline=c.now+c.ms.feedback;}return null;},
 advance(g,c){if(g.deadline===null||c.now<g.deadline)return;if(g.phase==='roundResult'){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}return;}const d=data(g);if(g.phase==='idle'){finish(g,'连续无人行动，等待 30 秒后当前轮中止，已完成轮成绩保留');return;}if(g.phase==='turn'){d.timeouts++;if(d.timeouts>=g.participants.length){g.phase='idle';g.notice='连续一轮无人行动；任意参赛玩家可继续，30 秒后中止本轮';turn(g,null,c.now+c.ms.offline);return;}}g.phase='turn';turn(g,nextOnline(g,c,g.currentPlayerId),c.now+c.ms.wallTurn);},
 snapshot(g){const d=data(g);return {position:{...d.position},obstacles:d.obstacles.map(h=>({...h})),countdown:d.countdown,breakUsed:d.breakUsed,radius:d.radius,last:d.last};},
};
