import type {RocketReport} from '@/lib/rocketReport';
import {ALL_POKEMON,getPokemon} from '../pokedex';
import {shuffleWith,type BatchModule,type BatchState,type BatchContext,turn,nextRound,finish,point} from './core';
export function graphemes(text:string){return Array.from(new Intl.Segmenter('zh',{granularity:'grapheme'}).segment(text)).length;}
export function validateClues(value:unknown,candidates:number[]):string|null {
 if(!Array.isArray(value)||value.length!==4||value.some(t=>typeof t!=='string'||graphemes(t.trim())<1||graphemes(t.trim())>8))return '四条暗号都须为 1–8 个可见字符';
 for(const t of value as string[]){const normalized=t.trim().toLowerCase();if(/\d|[一二三四五六七八九十]+号|第[一二三四]/u.test(normalized))return '请勿使用位置或图鉴编号';if(candidates.some(id=>{const p=getPokemon(id)!;return [p.nameZh,p.nameEn,...p.searchAliases??[]].some(n=>n.length>1&&normalized.includes(n.toLowerCase()));}))return '暗号不能直接包含候选的名称或明显别名';}return null;
}
interface Data {manual:boolean;excludedCount:number;reports:RocketReport[];candidates:number[];answer:number[];excluded:number[];sender:string;contact:string;attempt:number;draft:string[];clues:{attempt:number;texts:string[];missed:boolean;failed:boolean}[];guesses:Record<string,number[]>;guessDrafts:Record<string,number[]>;history:Record<string,{attempt:number;picks:number[]}[]>;result:{answer:number[];guesses:Record<string,number[]>;gains:Record<string,number>}|null;discussion:{playerId:string;text:string}[]}
const data=(g:BatchState)=>g.data as Data;
function begin(g:BatchState,c:BatchContext){
 const reports=(g.data as Data|null)?.reports??[],candidates=shuffleWith(ALL_POKEMON.map(p=>p.id),c.random).slice(0,16),manual=c.settings.rocketMode==='sender',answer=manual?[]:shuffleWith(candidates,c.random).slice(0,4),excluded=manual?[]:shuffleWith(candidates.filter(id=>!answer.includes(id)),c.random).slice(0,c.settings.rocketExcluded),index=(g.round-1)%g.participants.length;
 g.data={manual,excludedCount:c.settings.rocketExcluded,reports,candidates,answer,excluded,sender:g.participants[index],contact:g.participants[(index+1)%g.participants.length],attempt:1,draft:['','','',''],clues:[],guesses:{},guessDrafts:{},history:{},result:null,discussion:[]} satisfies Data;g.phase=manual?'setup':'transmit';turn(g,data(g).sender,c.now+c.ms.turn);
}
export function validateSelection(answer:unknown,excluded:unknown,candidates:number[],count:number,complete:boolean):string|null {
 if(!Array.isArray(answer)||!Array.isArray(excluded)||answer.length>4||excluded.length>count||complete&&(answer.length!==4||excluded.length!==count))return `请选择四只序列宝可梦和 ${count} 只排除项`;
 const all=[...answer,...excluded];if(all.some(id=>typeof id!=='number'||!candidates.includes(id))||new Set(all).size!==all.length)return '序列和排除项须来自候选，且不能重复或重叠';return null;
}
function lockSelection(g:BatchState,c:BatchContext,automatic=false){const d=data(g);if(automatic){d.answer.push(...shuffleWith(d.candidates.filter(id=>!d.answer.includes(id)&&!d.excluded.includes(id)),c.random).slice(0,4-d.answer.length));d.excluded.push(...shuffleWith(d.candidates.filter(id=>!d.answer.includes(id)&&!d.excluded.includes(id)),c.random).slice(0,d.excludedCount-d.excluded.length));g.notice='选题时间已到，未完成部分已随机补齐';}g.phase='transmit';turn(g,d.sender,c.now+c.ms.turn);}
function decode(g:BatchState,c:BatchContext,missed=false){const d=data(g);d.clues.push({attempt:d.attempt,texts:missed?[]:[...d.draft],missed,failed:false});d.guesses={};d.guessDrafts={};g.phase='decode';turn(g,null,c.now+c.ms.turn);}
function judge(g:BatchState,c:BatchContext){const d=data(g),correct=Object.entries(d.guesses).filter(([,picks])=>picks.every((p,i)=>p===d.answer[i])).map(([id])=>id),contact=correct.includes(d.contact),interceptors=correct.filter(id=>id!==d.contact),gains=Object.fromEntries(g.participants.map(id=>[id,0]));if(correct.length||d.attempt===5){if(contact){gains[d.sender]=interceptors.length?1:3;gains[d.contact]=interceptors.length?1:3;}for(const id of interceptors)gains[id]=2;for(const [id,n] of Object.entries(gains))point(g,id,n);d.result={answer:[...d.answer],guesses:structuredClone(d.guesses),gains};d.reports.push({round:g.round,sender:d.sender,contact:d.contact,participants:[...g.participants],answer:[...d.answer],clues:structuredClone(d.clues),history:structuredClone(d.history),gains:{...gains}});g.completedRounds++;g.phase='discussion';turn(g,null,null);}else{d.clues[d.clues.length-1].failed=true;d.attempt++;d.draft=['','','',''];g.phase='transmit';turn(g,d.sender,c.now+c.ms.turn);}}
export const rocketSecret:BatchModule={
 create(g,c){g.totalRounds=g.participants.length*(c.settings.rocketCycles||(g.participants.length===3?2:1));begin(g,c);},
 action(g,id,a,c){const d=data(g);if(g.phase==='discussion'){if(a.type==='next'&&id===c.hostId){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}return null;}if(a.type==='discuss'&&typeof a.text==='string'){const text=a.text.trim();if(!text||graphemes(text)>100)return '讨论内容须为 1–100 字';d.discussion.push({playerId:id,text});d.discussion=d.discussion.slice(-100);return null;}return '等待房主继续';}
 if(g.phase==='setup'){if(id!==d.sender)return '只有发报员能选择序列和排除项';if(a.type!=='selection-draft'&&a.type!=='lock-selection')return '请先选择序列和排除项';const error=validateSelection(a.answer,a.excluded,d.candidates,d.excludedCount,a.type==='lock-selection');if(error)return error;d.answer=[...(a.answer as number[])];d.excluded=[...(a.excluded as number[])];if(a.type==='lock-selection')lockSelection(g,c);return null;}
 if(g.phase==='transmit'){if(id!==d.sender)return '只有发报员能提交暗号';if(a.type!=='draft'&&a.type!=='transmit')return '请提交四条暗号';if(a.type==='draft'){if(!Array.isArray(a.texts)||a.texts.length!==4||a.texts.some(t=>typeof t!=='string'||graphemes(t)>100))return '草稿须为四条文本，每条不超过 100 字';}else{const error=validateClues(a.texts,d.candidates);if(error)return error;}d.draft=(a.texts as string[]).map(t=>t.trim());if(a.type==='transmit')decode(g,c);return null;}
 if(g.phase!=='decode'||id===d.sender||!g.participants.includes(id))return '当前不能破译';if(d.guesses[id])return '本次答案已锁定';const picks=a.picks;if(!['guess-draft','guess-sequence'].includes(String(a.type))||!Array.isArray(picks)||picks.length>4||a.type==='guess-sequence'&&picks.length!==4||new Set(picks).size!==picks.length||picks.some(p=>!d.candidates.includes(p)||id===d.contact&&d.excluded.includes(p)))return '请选择四只不同的合法候选';if(a.type==='guess-draft'){d.guessDrafts[id]=[...picks];return null;}d.guesses[id]=[...picks];(d.history[id]??=[]).push({attempt:d.attempt,picks:[...picks]});if(g.participants.filter(p=>p!==d.sender&&c.online.includes(p)).every(p=>d.guesses[p]))judge(g,c);return null;},
 advance(g,c){if(g.deadline===null||c.now<g.deadline)return;if(g.phase==='setup')lockSelection(g,c,true);else if(g.phase==='transmit')decode(g,c,!!validateClues(data(g).draft,data(g).candidates));else if(g.phase==='decode'){const d=data(g);for(const id of g.participants){const picks=d.guessDrafts[id];if(id!==d.sender&&!d.guesses[id]&&picks?.length===4){d.guesses[id]=[...picks];(d.history[id]??=[]).push({attempt:d.attempt,picks:[...picks]});}}judge(g,c);}},
 snapshot(g,id){const d=data(g),role=id===d.sender?'sender':id===d.contact?'contact':g.participants.includes(id)?'interceptor':'spectator';return {manual:d.manual,excludedCount:d.excludedCount,reports:structuredClone(g.phase==='final'?d.reports:d.result?d.reports.slice(-1):[]),...(d.result?{revealedHistory:structuredClone(d.history)}:{}),candidates:[...d.candidates],sender:d.sender,contact:d.contact,role,attempt:d.attempt,clues:d.clues.map(h=>({...h,texts:[...h.texts]})),submittedCount:Object.keys(d.guesses).length,myGuessDraft:[...d.guessDrafts[id]??[]],myGuess:d.guesses[id]?[...d.guesses[id]]:null,myHistory:structuredClone(d.history[id]??[]),...(role==='sender'||role==='contact'&&g.phase!=='setup'?{excluded:[...d.excluded]}:{}),...(role==='sender'?{answer:[...d.answer],draft:[...d.draft]}:{}),result:d.result?structuredClone(d.result):null,discussion:d.discussion.map(h=>({...h}))};},
};
