import {atGoal,automaticMove,moves,positions,same,wallError,type Pawn,type Wall} from '@/lib/quoridor';
import {finish,nextRound,point,turn,type BatchModule,type BatchState,type BatchContext} from './core';
interface WallData {firstPlayerIndex:number;pawns:Pawn[];walls:(Wall&{owner:string})[];remaining:Record<string,number>;finished:string[];forfeits:string[];timeouts:Record<string,number>;ranking:string[]|null;last:string|null}
const data=(g:BatchState)=>g.data as WallData;
function begin(g:BatchState,c:BatchContext){const firstPlayerIndex=g.round===1?Math.floor(c.random()*g.participants.length):data(g).firstPlayerIndex;g.data={firstPlayerIndex,pawns:positions(g.participants,g.round),walls:[],remaining:Object.fromEntries(g.participants.map(id=>[id,g.participants.length===2?10:g.participants.length===3?7:5])),finished:[],forfeits:[],timeouts:{},ranking:null,last:null} satisfies WallData;g.phase='turn';turn(g,g.participants[(firstPlayerIndex+g.round-1)%g.participants.length],c.now+c.ms.wallTurn);}
function settle(g:BatchState,c:BatchContext):boolean{const d=data(g);if(d.pawns.length>1)return false;const ranking=[...d.finished,...d.pawns.map(p=>p.id),...d.forfeits.slice().reverse()];const scores=g.participants.length===3?[3,1,0]:g.participants.length===2?[3,0]:[3,2,1,0];ranking.forEach((id,i)=>point(g,id,scores[i]));g.completedRounds++;d.ranking=ranking;g.phase='roundResult';turn(g,null,c.now+c.ms.feedback*2);return true;}
function progress(g:BatchState,c:BatchContext){const d=data(g);const previous=g.currentPlayerId;const pawn=d.pawns.find(p=>p.id===previous);if(pawn&&atGoal(pawn,pawn.goal)){d.finished.push(pawn.id);d.pawns=d.pawns.filter(p=>p.id!==pawn.id);d.remaining[pawn.id]=0;d.last=`${pawn.id} 到达目标，第 ${d.finished.length} 名`;}if(settle(g,c))return;const start=g.participants.indexOf(previous!);for(let k=1;k<=g.participants.length;k++){const id=g.participants[(start+k)%g.participants.length];if(d.pawns.some(p=>p.id===id)){turn(g,id,c.now+c.ms.wallTurn);return;}}}
export const sudowoodoQuoridor:BatchModule={
 create(g,c){if(![2,3,4].includes(g.participants.length))throw new Error('墙棋仅支持 2、3、4 人');g.totalRounds=c.settings.wallRounds;if(g.participants.length===3&&g.totalRounds%3!==0)throw new Error('三人局数须为 3 的倍数');begin(g,c);},
 action(g,id,a,c){const d=data(g);if(a.type==='end-match'){if(id!==c.hostId)return '只有房主能结束整场';finish(g,'房主结束整场，未完成局不计分');return null;}if(g.phase!=='turn'||g.currentPlayerId!==id)return '还没轮到你';const pawn=d.pawns.find(p=>p.id===id);if(!pawn)return '你已完成或弃权';if(a.type==='move'){const target={x:a.x as number,y:a.y as number};if(!moves(pawn,d.pawns,d.walls).some(p=>same(p,target)))return '不是合法落点';pawn.x=target.x;pawn.y=target.y;d.last=null;}else if(a.type==='wall'){if(d.remaining[id]<=0)return '没有剩余树才怪';const wall={x:a.x as number,y:a.y as number,orientation:a.orientation as 'H'|'V'};const error=wallError(wall,d.walls,d.pawns);if(error)return error;d.walls.push({...wall,owner:id});d.remaining[id]--;d.last=null;}else return '请选择移动或放置障碍';d.timeouts[id]=0;progress(g,c);return null;},
 advance(g,c){if(g.phase==='final'||g.deadline===null||c.now<g.deadline)return;const d=data(g);if(g.phase==='roundResult'){if(g.round>=g.totalRounds)finish(g);else{nextRound(g);begin(g,c);}return;}const id=g.currentPlayerId!;d.timeouts[id]=(d.timeouts[id]??0)+1;const pawn=d.pawns.find(p=>p.id===id);if(pawn){const target=automaticMove(pawn,d.pawns,d.walls);if(target){pawn.x=target.x;pawn.y=target.y;}d.last=id+" 超时，自动沿合法路线移动";}progress(g,c);},
 snapshot(g,id){const d=data(g);const pawn=d.pawns.find(p=>p.id===id);return {pawns:d.pawns.map(p=>({...p})),walls:d.walls.map(w=>({...w})),remaining:{...d.remaining},finished:[...d.finished],forfeits:[...d.forfeits],ranking:d.ranking,last:d.last,legalMoves:pawn?moves(pawn,d.pawns,d.walls):[],threePlayer:g.participants.length===3};},
 active(g){return data(g).pawns.map(p=>p.id);},
};
