'use client';
import {useEffect,useState} from 'react';
import type {BatchView} from '@/lib/secondTypes';
import type {RoomView} from '@/lib/types';
import {getPokemon} from '@/lib/pokemon';
type Tool='wide'|'focus'|'detector'|'scan';
const tools:Record<Tool,{name:string;price:number;hint:string}>={wide:{name:'广角镜',price:100,hint:'查看所选行或列的平均价值'},focus:{name:'焦点镜',price:150,hint:'查看箱中最高单卡价值'},detector:{name:'探宝器',price:100,hint:'查看箱中实际卡牌数量'},scan:{name:'扫描仪',price:50,hint:'查看所选格子的卡牌及价值'}};
interface Info {tool:Tool;text:string;bidRound:number}
interface Data {myCash:number;myFees:number;myTools:Info[];myInventory:{id:string;tool:Tool}[];myPurchases:number;myUsedThisRound:boolean;ready:string[];myBid:number|null;bidRound:number;submittedCount:number;publicInfo:Info[];lastBids:{highest:number;second:number;ratio:number}|null;result:{cards:(number|null)[];prices:number[];value:number;buyer:string|null;bid:number;tradeProfit:number;fees:Record<string,number>;net:Record<string,number>;bids:Record<string,number>}|null}
export function AuctionBoard({view,g,send,busy}:{view:RoomView;g:BatchView;send:(a:Record<string,unknown>)=>Promise<void>;busy:boolean}){
 const d=g.data as unknown as Data,[amount,setAmount]=useState('0'),[purchase,setPurchase]=useState<Tool|null>(null),[item,setItem]=useState<string|null>(null),[axis,setAxis]=useState('row'),[line,setLine]=useState(0),[cell,setCell]=useState<number|null>(null);useEffect(()=>{setAmount('0');setPurchase(null);setItem(null);setCell(null);},[g.turnId]);
 const mine=g.participants.includes(view.youId),intel=mine&&g.phase==='intel'&&!d.ready.includes(view.youId)&&!g.paused&&!busy,canBuy=intel&&d.bidRound===1&&d.myPurchases<2,chosen=d.myInventory.find(p=>p.id===item),canUse=intel&&!d.myUsedThisRound&&!!chosen,price=Number(amount),canBid=mine&&g.phase==='bid'&&d.myBid===null&&!g.paused&&!busy&&Number.isSafeInteger(price)&&price>=0&&price<=d.myCash;
 const name=(id:string)=>view.players.find(p=>p.id===id)?.nickname??'离线玩家';
 return <><h3>第 {d.bidRound}/3 轮 · {g.phase==='intel'?'情报操作':g.phase==='bid'?'秘密报价':'本箱揭晓'}</h3><p>你的现金 {d.myCash} · 本箱采购费 {d.myFees}</p><p className="muted">每箱第一轮可采购两件入背包，未使用道具保留到下一箱；每轮最多使用一件。所有人结束情报操作后才进入报价，报价期间不能用道具。</p>
 <div className="auction-public"><h3>📣 场外共同情报</h3>{d.publicInfo.map((info,i)=><p key={i}>第 {info.bidRound} 轮 · {tools[info.tool].name}：{info.text}</p>)}{g.phase==='intel'&&d.bidRound===2&&<p className="muted">第二轮没有新增公共情报。</p>}<small>第一轮和第三轮各随机一条，所有人共享，不占个人道具次数。</small></div>
 {d.lastBids&&<p>上轮未成交：最高 {d.lastBids.highest}，第二高 {d.lastBids.second}，所需倍率 {d.lastBids.ratio}，身份保密。</p>}
 <div className="auction-grid">{Array.from({length:25},(_,i)=>{const id=d.result?.cards[i],scope=chosen?.tool==='wide'&&(axis==='row'?Math.floor(i/5)===line:i%5===line);return <button key={i} className={`auction-cell${cell===i&&!d.result?' selected':''}${scope?' in-scope':''}`} disabled={!canUse||chosen?.tool!=='scan'||!!d.result} onClick={()=>setCell(i)} aria-label={`盲盒第 ${i+1} 格`}>{d.result?id===null?<span>空</span>:<><img src={`/pokemon/official-artwork/${id}.png`} alt={getPokemon(id!)?.nameZh} width={55} height={55}/><small>{d.result.prices[i]}</small></>:<span>{i+1}</span>}</button>;})}</div>
 {g.phase==='intel'&&<>{d.bidRound===1&&<><h3>道具商店（本箱已买 {d.myPurchases}/2 件）</h3><div className="auction-tools">{(Object.keys(tools) as Tool[]).map(tool=><button key={tool} className="btn" disabled={!canBuy||d.myCash<tools[tool].price} onClick={()=>{setPurchase(tool);setItem(null);}}>{tools[tool].name} · {tools[tool].price}</button>)}</div></>}
 {purchase&&<div className="third-result" role="group" aria-label="确认采购"><h3>采购 {tools[purchase].name}</h3><p>{tools[purchase].hint}。采购扣 {tools[purchase].price}，进入背包，使用时再选范围。</p><div className="row"><button className="btn btn-primary" disabled={!canBuy} onClick={()=>{void send({type:'buy-tool',tool:purchase});setPurchase(null);}}>确认采购入背包</button><button className="btn" onClick={()=>setPurchase(null)}>取消</button></div></div>}
 <h3>你的背包 {d.myUsedThisRound?'（本轮已使用道具）':'（本轮可用一件）'}</h3><div className="auction-tools">{d.myInventory.map(p=><button key={p.id} className={`btn${item===p.id?' btn-primary':''}`} disabled={!intel||d.myUsedThisRound} onClick={()=>{setItem(p.id);setPurchase(null);setCell(null);}}>{tools[p.tool].name} · 选择使用</button>)}</div>{!d.myInventory.length&&<p className="muted">背包为空。</p>}
 {chosen&&<div className="third-result" role="group" aria-label="选择道具作用范围"><h3>使用 {tools[chosen.tool].name}</h3><p>{tools[chosen.tool].hint}</p>{chosen.tool==='wide'&&<div className="row"><label>范围<select className="select" value={axis} onChange={e=>setAxis(e.target.value)}><option value="row">行</option><option value="column">列</option></select></label><label>编号<select className="select" value={line} onChange={e=>setLine(Number(e.target.value))}>{[0,1,2,3,4].map(i=><option key={i} value={i}>{i+1}</option>)}</select></label></div>}{chosen.tool==='scan'&&<p>{cell===null?'请先点击上方盲盒的一格。':`已选择第 ${cell+1} 格。`}</p>}<div className="row mt"><button className="btn btn-primary" disabled={!canUse||chosen.tool==='scan'&&cell===null} onClick={()=>{void send({type:'use-tool',itemId:chosen.id,axis,index:chosen.tool==='wide'?line:cell});setItem(null);}}>确认使用并消耗</button><button className="btn" onClick={()=>setItem(null)}>取消</button></div></div>}
 <button className="btn btn-primary btn-block mt" disabled={!intel} onClick={()=>send({type:'ready'})}>{d.ready.includes(view.youId)?'已结束情报操作，等待其他玩家':'结束情报操作，准备秘密报价'}</button><p>{d.ready.length}/{g.participants.length} 人已结束情报操作；超时自动结束。</p></>}
 {d.myTools.map((info,i)=><p key={i} className="third-result">私人情报 · 第 {info.bidRound} 轮：{info.text}</p>)}
 {g.phase==='bid'&&<><label>秘密报价（0 为弃价）<input className="input" type="number" min={0} max={d.myCash} value={amount} disabled={d.myBid!==null||!mine} onChange={e=>setAmount(e.target.value)}/></label><button className="btn btn-primary mt" disabled={!canBid} onClick={()=>send({type:'bid',amount:price})}>{d.myBid!==null?`已锁定 ${d.myBid}`:'确认提交，成交后必须购买'}</button><p>已提交 {d.submittedCount} 人；超时按 0 报价处理。</p></>}
 {d.result&&<div className="third-result"><h3>{d.result.buyer?`${name(d.result.buyer)} 成交`:'本箱流拍'}</h3><p>箱价值 {d.result.value} · 成交价 {d.result.bid} · 交易利润 {d.result.tradeProfit}</p>{g.participants.map(id=><p key={id}>{name(id)}：最终报价 {d.result!.bids[id]??0} · 采购费 {d.result!.fees[id]} · 本箱净收益 {d.result!.net[id]}</p>)}</div>}
 </>;
}
