'use client';
import {useEffect,useRef,useState} from 'react';
import type {RoomView} from '@/lib/types';
import type {BatchView} from '@/lib/secondTypes';
import type {RoomActions} from '@/lib/useRoom';
import {GAME_META} from '@/lib/types';
import {getPokemon} from '@/lib/pokemon';
import {Countdown,useNow,avatarColor} from '../Timer';
import {PokemonSelector} from '../PokemonSelector';
import type {Pawn,Point,Wall} from '@/lib/quoridor';
import {wallError} from '@/lib/quoridor';
import type {DriveMap,Vector,DriveInput} from '@/lib/driving';
import {ThirdGames} from './ThirdGames';
import {BerryTable} from './BerryTable';
import {GenderCompare} from './GenderCompare';
import {SoundButton,Blast,usePartySound} from './PartyEffects';
import {playPartySound} from '@/lib/partyAudio';
import {THIRD_GAMES} from '@/lib/secondTypes';
type Send=(a:Record<string,unknown>)=>Promise<void>;
type Props={view:RoomView;game:BatchView;actions:RoomActions};
const typeNames:Record<string,string>={normal:'一般',fire:'火',water:'水',electric:'电',grass:'草',ice:'冰',fighting:'格斗',poison:'毒',ground:'地面',flying:'飞行',psychic:'超能力',bug:'虫',rock:'岩石',ghost:'幽灵',dragon:'龙',dark:'恶',steel:'钢',fairy:'妖精'};
const Img=({id,size=90}:{id:number;size?:number})=><img src={`/pokemon/official-artwork/${id}.png`} alt={getPokemon(id)?.nameZh??'宝可梦'} width={size} height={size} style={{objectFit:'contain',maxWidth:'100%'}}/>;
const name=(v:RoomView,id:string)=>v.players.find(p=>p.id===id)?.nickname??'离线玩家';
export function BatchGame({view,game:g,actions}:Props){
 const [error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const mine=g.participants.includes(view.youId),turn=mine&&g.currentPlayerId===view.youId&&g.phase==='turn'&&!g.paused;
 const send:Send=async a=>{setBusy(true);const e=await actions.gameAction(a);setError(e);setBusy(false);};
 const final=g.phase==='final';
 return <div className="batch-layout"><div className="card"><div className="row" style={{justifyContent:'space-between'}}><h2>{GAME_META[g.game].icon} {GAME_META[g.game].name}</h2><span className="pill">{g.round}/{g.totalRounds}</span></div><p className="muted">{GAME_META[g.game].desc}</p>{!mine&&<p className="pill">正在旁观，下一场可以参加</p>}{g.paused?<p role="status">连接人数不足，等待重连（最多 30 秒）</p>:g.currentPlayerId&&!final&&<p className="center">{turn?'轮到你了':`${name(view,g.currentPlayerId)} 的回合`}</p>}{g.endsAt&&!g.paused&&<Countdown endsAt={g.endsAt}/>} {g.notice&&<p>{g.notice}</p>}<SoundButton/></div>
 {!final&&<div className="card">
 {THIRD_GAMES.includes(g.game as typeof THIRD_GAMES[number])&&<ThirdGames view={view} g={g} send={send} busy={busy}/>}
 {g.game==='type-bomb'&&<Bomb view={view} g={g} send={send} enabled={turn&&!busy}/>}
 {g.game==='starter-memory'&&<Memory view={view} g={g} send={send} enabled={turn&&!busy}/>}
 {g.game==='snorlax-berries'&&<BerryTable view={view} g={g} send={send} enabled={turn&&!busy}/>}
 {g.game==='electrode-relay'&&<Relay view={view} g={g} send={send}/>}
 {g.game==='gender-difference'&&<GenderCompare view={view} g={g} send={send} enabled={mine&&!busy&&!g.paused}/>}
 {g.game==='sudowoodo-quoridor'&&<Quoridor view={view} g={g} send={send} enabled={turn&&!busy}/>}
 {g.game==='drive-revavroom'&&<Drive view={view} g={g} send={send} enabled={mine&&!g.paused}/>}
 </div>}
 {error&&<div className="card" role="alert">{error}</div>}
 <div className="card"><h3>{final?'本场结算':'本场成绩'}{g.game==='drive-revavroom'?'（合作不计分）':''}</h3>{g.participants.slice().sort((a,b)=>g.points[b]-g.points[a]).map(id=><div key={id} className="row" style={{justifyContent:'space-between',padding:'8px 0'}}><span>{final&&g.ranks?`第 ${g.ranks[id]} 名 · `:''}{name(view,id)}{id===view.youId?'（你）':''}</span><strong>{g.points[id]}{final&&g.gains?` · 房间 +${g.gains[id]}`:''}</strong></div>)}{!final&&g.game!=='drive-revavroom'&&<p className="muted">整场结束后按累计成绩排名：冠军 100、亚军 50、季军 25；并列采用同名次。</p>}{final&&g.game==='drive-revavroom'&&<DriveResults g={g}/>}</div>
 {view.hostId===view.youId&&<div className="card">{!final&&g.game==='sudowoodo-quoridor'&&<button className="btn" onClick={()=>send({type:'end-match'})}>结束整场（当前局不计分）</button>}<button className="btn btn-block" onClick={actions.backToLobby}>{final?'返回大厅 / 再玩一场':'结束游戏并返回大厅'}</button></div>}</div>;
}
function Bomb({view,g,send,enabled}:{view:RoomView;g:BatchView;send:Send;enabled:boolean}){
 const d=g.data as {hearts:Record<string,number>;typeStatuses:Record<string,string>;history:{playerId:string;pokemonId:number|null;damage:number}[];allowedPokemon:number[];guessCount:number;reason:string|null;answer:{id:number;nameZh:string;types:string[]}|null};
 const colors:Record<string,string>={unknown:'#eef0f4',safe:'#bce8cc',possible:'#ffe5a0',dangerous:'#ffc6c6'};
 return <><div className="row" style={{justifyContent:'center'}}>{Object.entries(d.hearts).map(([id,h])=><span className="pill" key={id}>{name(view,id)} {'♥'.repeat(h)}{'♡'.repeat(2-h)}</span>)}</div><div className="batch-types">{Object.entries(d.typeStatuses).map(([t,s])=><span key={t} style={{background:colors[s],padding:'8px',borderRadius:8}}>{typeNames[t]??t}</span>)}</div><p className="muted">绿＝已确认安全 · 红＝必有 · 黄＝可能有 · 白＝尚未排除。相同属性组合全场本局只能用一次，不能选包含绿色属性的宝可梦。</p><p>有效猜测 {d.guessCount}/10</p><PokemonSelector allowedPokemon={d.allowedPokemon} disabled={!enabled} onSelect={p=>void send({type:'guess',pokemonId:p.id})} confirmLabel="确认猜测"/>{d.history.map((h,i)=><p key={i}>{name(view,h.playerId)}：{h.pokemonId===null?'操作超时':getPokemon(h.pokemonId)?.nameZh}，损失 {h.damage} 点生命</p>)}{d.answer&&<div className="center"><Img id={d.answer.id}/><p>答案：{d.answer.nameZh}（{d.answer.types.map(t=>typeNames[t]).join(' / ')}）</p><p>{d.reason}</p></div>}</>;
}
function Memory({view,g,send,enabled}:{view:RoomView;g:BatchView;send:Send;enabled:boolean}){
 const d=g.data as {remainingPairs:number;cards:{cardId:string;index:number;status:string;owner:string|null;pokemonId?:number}[]};
 usePartySound(d.cards.filter(c=>c.status!=='back').map(c=>c.index).join(',')||null,'flip');
 return <><p>还剩 {d.remainingPairs} 对 · 每次翻两张，配对成功奖励继续翻；失败或超时换人</p><div className={`memory-grid${d.cards.length>18?' large':''}`}>{d.cards.map(c=><button key={c.cardId} className={`memory-card ${c.status}`} aria-label={c.status==='back'?`翻开第 ${c.index+1} 张牌`:getPokemon(c.pokemonId!)?.nameZh} disabled={!enabled||c.status!=='back'} onClick={()=>send({type:'flip',index:c.index})} style={c.owner?{borderColor:avatarColor(c.owner)}:{}}>{c.pokemonId?<><Img id={c.pokemonId} size={70}/>{c.owner&&<small>{name(view,c.owner)}</small>}</>:<span>?</span>}</button>)}</div></>;
}
function Relay({view,g,send}:{view:RoomView;g:BatchView;send:Send}){
 const d=g.data as {holder:string;possessionId:string;expression:string;pressStartedAt:number|null;last:{playerId:string;gain:number;type:string;targetId?:string}|null},now=useNow(50),press=useRef(false),[localPressed,setPressed]=useState(false);
 const current=useRef({send,d});current.current={send,d};
 useEffect(()=>{press.current=false;setPressed(false);},[d.possessionId]);
 useEffect(()=>{const cancel=()=>{if(press.current){press.current=false;setPressed(false);void current.current.send({type:'cancel',possessionId:current.current.d.possessionId});}};const hidden=()=>{if(document.hidden)cancel();};window.addEventListener('blur',cancel);document.addEventListener('visibilitychange',hidden);return()=>{cancel();window.removeEventListener('blur',cancel);document.removeEventListener('visibilitychange',hidden);};},[]);
 const holding=g.phase==='hold'&&d.holder===view.youId&&!g.paused;const danger=d.expression==='紧张'?'danger':d.expression==='警觉'?'warning':'calm';usePartySound(d.last?g.roundId+g.turnId+d.last.type:null,d.last?.type==='explode'?'explode':'charge');useEffect(()=>{if(g.phase!=='hold'||g.paused||danger==='calm')return;const timer=setInterval(()=>playPartySound('pulse'),danger==='danger'?500:1300);return()=>clearInterval(timer);},[danger,g.phase,g.paused]);
 return <div className="center"><div className={`relay-orb ${danger}`}><span className="relay-aura"/><Img id={101} size={160}/><span className="relay-electric">ϟ</span></div><h3>{g.phase==='roundResult'?'💥 雷弹爆炸':`${name(view,d.holder)} 正持有雷弹`}</h3><p>状态：{d.expression}</p><button className="btn btn-primary relay-charge" disabled={!holding} onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{if(!holding)return;e.currentTarget.setPointerCapture(e.pointerId);press.current=true;setPressed(true);playPartySound('charge');void send({type:'press',possessionId:d.possessionId});}} onPointerUp={()=>{if(!press.current)return;press.current=false;setPressed(false);void send({type:'release',possessionId:d.possessionId});}} onPointerCancel={()=>{press.current=false;setPressed(false);void send({type:'cancel',possessionId:d.possessionId});}}>{localPressed?`蓄力 ${d.pressStartedAt===null?'…':((now-d.pressStartedAt)/1000).toFixed(1)+'s'} · 松手传递`:'按住蓄力，松手传递'}</button><p className="muted">至少按住 0.5 秒才能传递；达到 2 秒传递得 1 分。持有者爆炸 −3 分，爆炸倒计时保密。</p>{g.phase==='roundResult'&&<Blast key={g.roundId} label={name(view,d.holder)+' 被雷弹炸中 · −3 分'}/>} {d.last&&<p>{name(view,d.last.playerId)} {d.last.type==='explode'?'爆炸了':`传给 ${name(view,d.last.targetId!)}`}，{d.last.gain>0?'+':''}{d.last.gain} 分</p>}</div>;
}
function Quoridor({view,g,send,enabled}:{view:RoomView;g:BatchView;send:Send;enabled:boolean}){
 const d=g.data as {pawns:Pawn[];walls:(Wall&{owner:string})[];remaining:Record<string,number>;legalMoves:Point[];last:string|null;ranking:string[]|null},[mode,setMode]=useState<'move'|'H'|'V'>('move'),[preview,setPreview]=useState<Wall|null>(null);
 useEffect(()=>{setPreview(null);setMode('move');},[g.turnId]);const invalid=preview?wallError(preview,d.walls,d.pawns):null;const colors=(id:string)=>avatarColor(id);
 return <><div className="row" style={{justifyContent:'center'}}>{(['move','H','V'] as const).map(m=><button className={`btn${mode===m?' btn-primary':''}`} disabled={!enabled} key={m} onClick={()=>{setMode(m);setPreview(null);}}>{m==='move'?'移动':m==='H'?'横墙':'竖墙'}</button>)}</div><p className="muted center">{mode==='move'?'点击高亮格子移动；棋子颜色对应玩家。':'点击棋盘格间的墙位预览，再确认放置。'} 到达自己的对岸即可获胜。</p><div className="wall-board"><svg viewBox="0 0 450 450" role="group" aria-label="九乘九墙棋棋盘" style={{width:'100%',display:'block'}}>{Array.from({length:81},(_,i)=>{const x=i%9,y=Math.floor(i/9),legal=enabled&&d.legalMoves.some(p=>p.x===x&&p.y===y);return <rect key={i} x={x*50+4} y={y*50+4} width={42} height={42} rx={5} fill={legal?'#c8e9dc':'#f0ede5'} stroke="#d9d4c8" role={mode==='move'?'button':undefined} aria-label={`格子 ${x+1},${y+1}${legal?'，可移动':''}`} tabIndex={legal?0:-1} onClick={()=>{if(legal&&mode==='move')void send({type:'move',x,y});}} onKeyDown={e=>{if(legal&&mode==='move'&&(e.key==='Enter'||e.key===' '))void send({type:'move',x,y});}}/>;})}{d.pawns.map(p=><g key={p.id}><circle cx={p.x*50+25} cy={p.y*50+25} r={15} fill={colors(p.id)}/><text x={p.x*50+25} y={p.y*50+30} textAnchor="middle" fontSize={13} fill="white">{name(view,p.id).slice(0,1)}</text></g>)}{d.walls.map((w,i)=><rect key={i} x={w.orientation==='H'?w.x*50+3:w.x*50+46} y={w.orientation==='H'?w.y*50+46:w.y*50+3} width={w.orientation==='H'?94:8} height={w.orientation==='H'?8:94} rx={3} fill={colors(w.owner)}/>)}{enabled&&mode!=='move'&&Array.from({length:64},(_,i)=>{const x=i%8,y=Math.floor(i/8);return <rect key={`anchor${i}`} x={mode==='H'?x*50+4:x*50+41} y={mode==='H'?y*50+41:y*50+4} width={mode==='H'?42:18} height={mode==='H'?18:42} fill="rgba(80,120,80,.22)" role="button" tabIndex={0} aria-label={`预览${mode==='H'?'横':'竖'}墙 ${x+1},${y+1}`} onClick={()=>setPreview({x,y,orientation:mode})} onKeyDown={e=>{if(e.key==='Enter')setPreview({x,y,orientation:mode});}}/>;})}{preview&&<rect x={preview.orientation==='H'?preview.x*50+3:preview.x*50+46} y={preview.orientation==='H'?preview.y*50+46:preview.y*50+3} width={preview.orientation==='H'?94:8} height={preview.orientation==='H'?8:94} fill={invalid?'#f44':'#3a8'} opacity={.7} pointerEvents="none"/>}</svg></div>{preview&&<div className="row"><span>{invalid??'合法墙位'}</span><button className="btn btn-primary" disabled={!enabled||!!invalid} onClick={()=>send({type:'wall',...preview})}>确认放置</button><button className="btn" onClick={()=>setPreview(null)}>取消</button></div>}<div className="batch-player-key">{g.participants.map(id=><p key={id} style={{borderLeft:`5px solid ${colors(id)}`,paddingLeft:8}}>{name(view,id)} · 剩余 {d.remaining[id]} 墙 · {d.pawns.find(p=>p.id===id)?.goal?`目标：${({top:'上边',bottom:'下边',left:'左边',right:'右边'})[d.pawns.find(p=>p.id===id)!.goal]}`:'已结束本局'}</p>)}</div>{d.last&&<p>{d.last.replaceAll(g.currentPlayerId??'__',name(view,g.currentPlayerId??''))}</p>}{d.ranking&&<p>本局名次：{d.ranking.map(id=>name(view,id)).join(' → ')}</p>}</>;
}
function DriveResults({g}:{g:BatchView}){const d=g.data as {results:{mapId:string;success:boolean;elapsed:number}[]};return <>{d.results.map((r,i)=><p key={i}>地图 {i+1}：{r.success?'成功':'超时'} · {(r.elapsed/1000).toFixed(1)} 秒</p>)}</>;}
function Drive({view,g,send,enabled}:{view:RoomView;g:BatchView;send:Send;enabled:boolean}){
 const d=g.data as {map:DriveMap;position:Vector;velocity:Vector;inputs:Record<string,DriveInput|null>;elapsed:number},seq=useRef(0),sender=useRef(send),state=useRef({enabled,phase:g.phase});sender.current=send;state.current={enabled,phase:g.phase};const sprite=useRef<SVGImageElement|null>(null),samples=useRef<{from:Vector;to:Vector;at:number}>({from:d.position,to:d.position,at:0});
 useEffect(()=>{seq.current=0;},[g.roundId]);
 useEffect(()=>{samples.current={from:samples.current.to,to:d.position,at:performance.now()};},[d.position.x,d.position.y]);
 useEffect(()=>{let frame=0;const draw=()=>{const s=samples.current,t=Math.min(1,Math.max(0,(performance.now()-s.at)/75)),x=s.from.x+(s.to.x-s.from.x)*t,y=s.from.y+(s.to.y-s.from.y)*t;sprite.current?.setAttribute('x',String(x-18));sprite.current?.setAttribute('y',String(y-18));frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame);},[g.roundId]);
 const input=(key:DriveInput)=>{if(!state.current.enabled||!['prepare','play'].includes(state.current.phase))return;void sender.current({type:'input',key,inputSeq:++seq.current});};
 useEffect(()=>{const keys:Record<string,DriveInput>={ArrowUp:'up',w:'up',ArrowRight:'right',d:'right',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left'};const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select')||e.repeat)return;const value=keys[e.key];if(value){e.preventDefault();input(value);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 return <><h3 className="center">地图 {g.round} · {d.map.name}</h3><p className="muted center">你是晃晃斑，晕乎乎地坐上噗隆隆姆，已经分不清方向！你的方向键与实际行驶方向错乱了，先试探，再和伙伴一起开到终点。</p><p className="center">{g.phase==='prepare'?'请选择初始方向，三秒后出发':g.phase==='mapResult'?'本地图结束，即将前往下一张':'一起把车开进绿色目标区'}</p><svg viewBox={`0 0 ${d.map.bounds.width} ${d.map.bounds.height}`} className="drive-map" role="img" aria-label="驾驶地图"><rect width={d.map.bounds.width} height={d.map.bounds.height} rx={10} fill="#eef2e7"/><rect {...d.map.goal} fill="#74c799" rx={8}/>{d.map.walls.map((w,i)=><rect {...w} key={i} fill="#7b8374" rx={2}/>)}<image ref={sprite} href="/pokemon/official-artwork/966.png" x={d.position.x-18} y={d.position.y-18} width={36} height={36}/></svg><div className="drive-controls">{(['up','left','down','right'] as DriveInput[]).map(key=><button key={key} className={`btn${d.inputs[view.youId]===key?' btn-primary':''}`} disabled={!enabled||!['prepare','play'].includes(g.phase)} aria-label={`方向 ${key}`} onPointerDown={e=>{e.preventDefault();input(key);}} onPointerEnter={e=>{if(e.buttons===1)input(key);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')input(key);}}>{({up:'↑',left:'←',down:'↓',right:'→'})[key]}</button>)}</div><p className="muted">点击或拖过按键选择方向，松手后保持。也支持方向键 / WASD。每个人的真实方向都不同；方向抵消则停车。</p><div className="row">{g.participants.map(id=><span className="pill" key={id}>{name(view,id)}：{d.inputs[id]?({up:'↑',left:'←',down:'↓',right:'→'})[d.inputs[id]!]: '未选择'}</span>)}</div><DriveResults g={g}/></>;
}



