'use client';
import {useEffect,useRef,useState} from 'react';
import type {BatchView} from '@/lib/secondTypes';
import type {RoomView} from '@/lib/types';
import {useNow} from '../Timer';
interface Rect {x:number;y:number;width:number;height:number}
export function GenderCompare({view,g,send,enabled}:{view:RoomView;g:BatchView;send:(a:Record<string,unknown>)=>Promise<void>;enabled:boolean}){
 const d=g.data as {images:string[];ready:boolean;cooldownEndsAt:number;solved:boolean;errors:number;score:number;hit:{side:number;x:number;y:number}|null;detail?:string;regions?:{male:Rect[];female:Rect[]}},now=useNow(),[zoom,setZoom]=useState(1),[point,setPoint]=useState<{side:number;x:number;y:number}|null>(null),sent=useRef(''),sender=useRef(send),panes=useRef<(HTMLDivElement|null)[]>([]),syncing=useRef(false),down=useRef<{x:number;y:number}|null>(null);sender.current=send;
 useEffect(()=>{setZoom(1);setPoint(null);panes.current.forEach(p=>{if(p){p.scrollTop=0;p.scrollLeft=0;}});},[g.roundId]);
 useEffect(()=>{if(g.phase!=='loading'||!g.participants.includes(view.youId)||sent.current===g.roundId)return;sent.current=g.roundId;let cancelled=false;Promise.all(d.images.map(src=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve();img.onerror=()=>reject();img.src=src;}))).then(()=>{if(!cancelled)void sender.current({type:'assets-ready'});}).catch(()=>{if(!cancelled)void sender.current({type:'asset-failed'});});return()=>{cancelled=true;};},[g.roundId,g.phase,view.youId,d.images.join('|')]);
 const revealed=g.phase==='reveal',canPick=enabled&&g.phase==='question'&&!d.solved&&now>=d.cooldownEndsAt;
 const synchronize=(side:number)=>{if(syncing.current)return;const p=panes.current[side],other=panes.current[1-side];if(p&&other&&(Math.abs(other.scrollLeft-p.scrollLeft)>1||Math.abs(other.scrollTop-p.scrollTop)>1)){syncing.current=true;other.scrollLeft=p.scrollLeft;other.scrollTop=p.scrollTop;requestAnimationFrame(()=>syncing.current=false);}};
 const click=(side:number,x:number,y:number)=>{if(canPick){setPoint({side,x,y});void send({type:'spot',side,x,y});}};
 return <><h3 className="center">{g.phase==='loading'?'正在加载两张图片…':d.solved?`已找对 · ${d.score} 分`:'左右哪里不一样？'}</h3><label className="compare-zoom">同步放大 {zoom.toFixed(1)}×<input aria-label="同步放大" type="range" min={1} max={3} step={.25} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><p className="muted">可以点击任意一边的差异部位。放大后滑动图片，两边同步移动；120 秒内作答。</p>
 <div className="gender-comparison">{d.images.map((src,side)=><div key={src}><strong>{revealed?(side===0?'雄性':'雌性'):(side===0?'左图':'右图')}</strong><div className="compare-pane" ref={p=>{panes.current[side]=p;}} onScroll={()=>synchronize(side)}><svg viewBox="0 0 512 512" className="compare-picture" style={{width:zoom*100+'%',maxWidth:'none'}} role="group" aria-label={side===0?'左侧宝可梦图片':'右侧宝可梦图片'} onPointerDown={e=>{down.current={x:e.clientX,y:e.clientY};}} onPointerUp={e=>{if(!down.current||Math.hypot(e.clientX-down.current.x,e.clientY-down.current.y)>7){down.current=null;return;}down.current=null;const rect=e.currentTarget.getBoundingClientRect();click(side,(e.clientX-rect.left)/rect.width,(e.clientY-rect.top)/rect.height);}}><image href={src} width={512} height={512} aria-label={side===0?'左图宝可梦':'右图宝可梦'}/>{revealed&&d.regions?.[side===0?'male':'female'].map((r,i)=><rect key={i} x={r.x*512} y={r.y*512} width={r.width*512} height={r.height*512} rx={12} fill="none" stroke="#21a56e" strokeWidth={7}/>)}{(d.hit??point)?.side===side&&<circle cx={(d.hit??point)!.x*512} cy={(d.hit??point)!.y*512} r={15} fill="none" stroke={d.solved?'#21a56e':'#df8333'} strokeWidth={5}/>}</svg></div></div>)}</div>
 {now<d.cooldownEndsAt&&<p role="status">这里不是差异部位，{Math.ceil((d.cooldownEndsAt-now)/1000)} 秒后可再试</p>}<p className="muted">点击差异所在部位即可，不必精确到细小像素。答错扣 20 分、冷却 2 秒；超时本题 0 分并揭晓。</p>{revealed&&<div className="third-result"><h3>差异揭晓</h3><p>{d.detail}</p></div>}</>;
}
