'use client';
import React,{useState} from 'react';
import type {RoomView} from '@/lib/types';
import {getPokemon} from '@/lib/pokemon';
import {copyText} from '@/lib/clipboard';
import {rocketGuess,rocketReportText,type RocketReport} from '@/lib/rocketReport';
const playerName=(view:RoomView,id:string)=>view.players.find(p=>p.id===id)?.nickname??'离线玩家';
const pokemonName=(id:number)=>getPokemon(id)?.nameZh??`#${id}`;
export function RocketAttemptReview({view,report,attempt}:{view:RoomView;report:RocketReport;attempt:number}){return <details className="rocket-review"><summary>展开第 {attempt} 次所有人的猜测</summary>{report.participants.filter(id=>id!==report.sender).map(id=>{const picks=rocketGuess(report,id,attempt),matches=picks?.filter((p,i)=>p===report.answer[i]).length??0;return <div className="third-result" key={id}><strong>{playerName(view,id)} · {id===report.contact?'接头员':'截获者'}</strong><p>{picks?picks.map(pokemonName).join(' → '):'未提交（超时或断线）'}</p>{picks&&<small>{matches===4?'✓ 完全正确':`位置正确 ${matches}/4`}</small>}</div>;})}</details>;}
export function RocketReportCopy({view,reports}:{view:RoomView;reports:RocketReport[]}){const [status,setStatus]=useState<'idle'|'copied'|'manual'>('idle');const text=rocketReportText(view.code,reports,id=>playerName(view,id),pokemonName);return <div className="rocket-report-copy"><button className="btn btn-primary" onClick={async()=>setStatus(await copyText(text)?'copied':'manual')}>{status==='copied'?'✓ 战报已复制':reports.length===1?'复制本题战报':'复制整场战报'}</button><p role="status" aria-live="polite">{status==='copied'?'可以粘贴到聊天中复盘和分享。':status==='manual'?'自动复制未成功，请选中下面的战报手动复制。':''}</p><details open={status==='manual'}><summary>查看文字战报</summary><textarea aria-label="文字战报" className="input" readOnly value={text} rows={12} onFocus={e=>e.currentTarget.select()} style={{whiteSpace:'pre-wrap',resize:'vertical'}}/></details></div>;}
export function RocketMatchReview({view,reports}:{view:RoomView;reports:RocketReport[]}){return <div className="card"><h3>火箭队行动复盘 · {reports.length} 题</h3><RocketReportCopy view={view} reports={reports}/>{reports.map(report=><details key={report.round} className="rocket-review"><summary>第 {report.round} 题 · {playerName(view,report.sender)} 发报</summary><p>正确序列：{report.answer.map(pokemonName).join(' → ')}</p>{report.clues.map(clue=><div className="third-result" key={clue.attempt}><strong>第 {clue.attempt} 次发报</strong><p>{clue.missed?'未成功发报，沿用已有暗号':clue.texts.map((t,i)=>`${i+1}. ${t}`).join(' · ')}</p><RocketAttemptReview view={view} report={report} attempt={clue.attempt}/></div>)}</details>)}</div>;}
