'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {pauseMusic,setMusicVolume,startMusic} from '@/lib/partyMusic';
import {audioEnabled,effectsVolume,setAudioEnabled,setEffectsVolume,unlockPartyAudio,playPartySound} from '@/lib/partyAudio';
type MusicState={enabled:boolean;volume:number;error:string|null;toggle:()=>Promise<void>;changeVolume:(value:number)=>void};
const MusicContext=createContext<MusicState|null>(null);
export function PartyMusicProvider({children}:{children:ReactNode}){
 const [enabled,setEnabled]=useState(false),[volume,setVolume]=useState(25),[error,setError]=useState<string|null>(null),intent=useRef(false),busy=useRef(false);
 useEffect(()=>{try{const saved=localStorage.getItem('ppt-music-volume');const n=saved===null?25:Number(saved);if(Number.isFinite(n)){setVolume(Math.max(0,Math.min(100,n)));setMusicVolume(n);}}catch{}const unlock=()=>{void unlockPartyAudio().catch(()=>{});};window.addEventListener('pointerdown',unlock);window.addEventListener('keydown',unlock);const visibility=()=>{if(document.hidden)pauseMusic();else if(intent.current)void startMusic().catch(()=>{intent.current=false;setEnabled(false);setError('请点击重新开启音乐');});};document.addEventListener('visibilitychange',visibility);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pointerdown',unlock);window.removeEventListener('keydown',unlock);intent.current=false;pauseMusic();};},[]);
 const toggle=async()=>{if(busy.current)return;setError(null);if(intent.current){intent.current=false;setEnabled(false);pauseMusic();return;}busy.current=true;try{setMusicVolume(volume);await startMusic();intent.current=true;setEnabled(true);}catch{setError('浏览器暂时无法播放，请点击重试');}finally{busy.current=false;}};
 const changeVolume=(value:number)=>{setVolume(value);setMusicVolume(value);try{localStorage.setItem('ppt-music-volume',String(value));}catch{}};
 return <MusicContext.Provider value={{enabled,volume,error,toggle,changeVolume}}>{children}</MusicContext.Provider>;
}
export function PartyMusicControl(){const state=useContext(MusicContext),[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),[effectsOn,setEffectsOn]=useState(false),[fxVolume,setFxVolume]=useState(55),[fxError,setFxError]=useState<string|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem('ppt-effects-volume');if(saved!==null&&Number.isFinite(Number(saved)))setEffectsVolume(Number(saved));}catch{}const refresh=()=>{setEffectsOn(audioEnabled());setFxVolume(effectsVolume());};refresh();window.addEventListener('ppt-audio-change',refresh);return()=>window.removeEventListener('ppt-audio-change',refresh);},[]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[open]);
 if(!state)return null;
 return <div className="music-control" ref={root}><button className={`btn btn-sm music-button${state.enabled||effectsOn?' music-on':''}`} aria-label="声音设置" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span aria-hidden="true">♪</span><span className="music-label">{state.enabled||effectsOn?'声音已开启':'声音'}</span></button>{open&&<div className="music-panel" role="region" aria-label="音乐与音效设置"><div className="row" style={{justifyContent:'space-between'}}><strong>音乐与音效</strong><button className="btn btn-sm" onClick={()=>setOpen(false)} aria-label="关闭声音设置">关闭</button></div><p className="muted">轻柔的合成旋律，陪你开一桌派对。</p><button className="btn btn-primary btn-block" aria-pressed={state.enabled} onClick={()=>void state.toggle()}>{state.enabled?'暂停音乐':'开启音乐'}</button><label className="music-volume">音乐音量 <span>{state.volume}%</span><input type="range" min={0} max={100} value={state.volume} aria-label="音乐音量" onChange={e=>state.changeVolume(Number(e.target.value))}/></label><hr className="home-divider"/><button className="btn btn-block" aria-pressed={effectsOn} onClick={()=>{setFxError(null);void setAudioEnabled(!effectsOn).then(()=>{if(!effectsOn)playPartySound('correct');}).catch(()=>setFxError('音效暂时无法播放，请点击重试'));}}>{effectsOn?'关闭游戏音效':'开启游戏音效'}</button><label className="music-volume">音效音量 <span>{fxVolume}%</span><input type="range" min={0} max={100} value={fxVolume} aria-label="音效音量" onChange={e=>setEffectsVolume(Number(e.target.value))}/></label><p className="muted">默认关闭，可分别调整音量。切到其他标签页时，背景音乐自动暂停。</p>{fxError&&<p role="alert">{fxError}</p>}{state.error&&<p role="alert">{state.error}</p>}</div>}</div>;
}
