import {writeFileSync} from 'node:fs';
import {makeBox,cardValue,auctionWinner,AUCTION} from '../src/server/batch/auction';
let seed=4141;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const boxes=Array.from({length:10000},()=>makeBox(random));
const values=boxes.map(b=>b.reduce<number>((s,id)=>s+(id===null?0:cardValue(id)),0)).sort((a,b)=>a-b);
const mean=(a:number[])=>a.reduce((s,v)=>s+v,0)/a.length;
const quant=(a:number[],p:number)=>a[Math.floor((a.length-1)*p)];
const avgCard=mean(boxes.flat().filter((id):id is number=>id!==null).map(cardValue));
const distribution={samples:boxes.length,mean:mean(values),median:quant(values,.5),p10:quant(values,.1),p90:quant(values,.9),p99:quant(values,.99),meanCards:mean(boxes.map(b=>b.filter(id=>id!==null).length)),meanTopCardFraction:mean(boxes.map(b=>{const v=b.map(id=>id===null?0:cardValue(id));return Math.max(...v)/v.reduce((s,n)=>s+n,0);})),averageCardValue:avgCard};
const strategies=['conservative','aggressive','detector','minimum','shill'] as const;
const runs:any[]=[];
for(const n of [3,4,8])for(const strategy of strategies){const ends:number[]=[],targets:number[]=[],roi:number[]=[];let unsold=0,total=0,bankrupt=0;for(let match=0;match<1000;match++){const cash=Array(n).fill(AUCTION.startingCash),fees=Array(n).fill(0);let noSales=0;for(let round=0;round<15;round++){const box=boxes[(match*15+round)%boxes.length],v=box.reduce<number>((s,id)=>s+(id===null?0:cardValue(id)),0);const ids=cash.map((_,i)=>String(i));const bids:Record<string,number>={};for(let i=0;i<n;i++){const policy=i===0?strategy:(i%2?'conservative':'aggressive');let estimate=11.5*avgCard;if(policy==='detector'&&cash[i]>=100){cash[i]-=100;fees[i]+=100;estimate=box.filter(id=>id!==null).length*avgCard;}const multiplier=policy==='minimum'?.00001:policy==='aggressive'?.95:policy==='shill'?1.1:.65;bids[String(i)]=Math.min(cash[i],Math.max(1,Math.round(estimate*multiplier*(.8+.4*random()))));}let buyer:string|null=null;for(let bidRound=1;bidRound<=3;bidRound++){buyer=auctionWinner(bids,bidRound,random);if(buyer)break;}total++;if(buyer){const i=Number(buyer);cash[i]+=v-bids[buyer];noSales=0;}else{unsold++;noSales++;}if(cash.some(x=>x>=15000)){targets.push(round+1);break;}if(noSales>=3||cash.every(x=>x===0))break;}ends.push(cash[0]);roi.push(cash[0]-10000);if(cash[0]===0)bankrupt++;}const sorted=ends.sort((a,b)=>a-b);runs.push({players:n,strategy,matches:1000,targetReachRate:targets.length/1000,meanBoxesToAnyTarget:targets.length?mean(targets):null,noSaleRate:unsold/total,bankruptcyRate:bankrupt/1000,meanEndingCash:mean(ends),cashP10:quant(sorted,.1),cashMedian:quant(sorted,.5),cashP90:quant(sorted,.9),meanNetAfterToolFees:mean(roi)});}
const report={seed:4141,parameters:AUCTION,distribution,runs,limitations:['Automated heuristic strategies, not optimal play or human balance validation.','Eight-player runs are stress simulations; production auction supports at most six.','Minimum bidder tested against competing positive bidders. If everyone else bids zero, bid 1 necessarily wins by the specified single-positive-bid rule.','Tool results estimated from card count only; results do not establish causal ROI for all four tools.','Three-person human balance trial remains pending.'],status:'Unbalanced V0.1 experimental values; do not claim human validation.'};
writeFileSync('data/auction-simulation.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({distribution,runs,status:report.status},null,2));
