import assert from 'node:assert/strict';
import {MODULES} from '../src/server/batch';
import {SECOND_DEFAULTS,type SecondGameType} from '../src/lib/secondTypes';
import {type BatchState,type BatchContext} from '../src/server/batch/core';
import {CARD_TIERS,AUCTION_TOOLS,cardTier,knownValueFloor} from '../src/lib/auction';
import {cardValue} from '../src/server/batch/auction';
import {ALL_POKEMON} from '../src/server/pokedex';
import {adventureDeck} from '../src/lib/greed';
import {previewTrap,HEX_DIRECTIONS,hexKey,hexDistance,escapePath} from '../src/lib/meloetta';
let checks=0,seed=169;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};const check=(v:unknown,l:string)=>{assert.ok(v,l);checks++;};
const c:BatchContext={now:1000,random,online:['a','b','c'],hostId:'a',settings:{...SECOND_DEFAULTS,auctionBoxes:1,luckRounds:1,diceMatches:1},ms:{turn:120000,wallTurn:120000,feedback:1500,memoryReveal:2000,question:120000,questionReveal:3000,prepare:3000,bombRound:180000,offline:30000,relayMin:20000,relayMax:40000,driveSecond:1000}};
function state(kind:SecondGameType){const g:BatchState={kind,timers:[],matchId:'m',roundId:'r',turnId:'t',phase:'',round:1,totalRounds:1,deadline:null,currentPlayerId:null,participants:['a','b','c'],points:{a:0,b:0,c:0},ranks:null,gains:null,notice:null,pausedAt:null,onlineIds:[],processed:new Map(),awarded:false,completedRounds:0,data:null};MODULES[kind].create(g,c);return g;}
const act=(g:BatchState,id:string,a:Record<string,unknown>)=>MODULES[g.kind].action(g,id,a.type==='open'?{...a,expectedHand:(g.data as any).hand,expectedCall:(g.data as any).call}:a,c),snap=(g:BatchState,id='a')=>MODULES[g.kind].snapshot(g,id,c) as any,ready=(g:BatchState)=>{for(const id of c.online)check(act(g,id,{type:'ready'})===null,'phase ready');};
// Exhaust every ordinary face, equality boundary, successful/failed challenges and each seat.
const starters=new Set<string>();for(let n=0;n<240;n++){const g=state('pokemon-liars-dice'),d=g.data as any;starters.add(g.currentPlayerId!);const face=n%5,actual=n%16;d.dice={a:[],b:[],c:[]};for(let k=0;k<15;k++)d.dice[g.participants[Math.floor(k/5)]].push(k<actual?(k%2?5:face):(face+1)%5);const caller=g.currentPlayerId!,count=Math.min(15,Math.max(1,actual+(n%3-1))),before={...d.lives};check(act(g,caller,{type:'call',count,face})===null,'caller legal');const challenger=g.currentPlayerId!;check(act(g,challenger,{type:'open'})===null,'challenge accepted');const result=snap(g).result,holds=Math.min(actual,15)>=count,loser=holds?challenger:caller;check(result.loser===loser&&result.holds===holds,'correct seat loses');check(g.participants.every(id=>d.lives[id]===before[id]-(id===loser?1:0)),'only expected loser loses exactly one life');check(result.ordinary+result.wild===result.actual,'explicit wild formula');check(act(g,challenger,{type:'open'})!==null&&d.lives[loser]===before[loser]-1,'duplicate open cannot double damage');result.livesAfter[loser]=99;check(d.lives[loser]!==99&&d.results[0].livesAfter[loser]!==99,'snapshot and history immutable');MODULES[g.kind].advance(g,{...c,now:g.deadline!});check(g.currentPlayerId===loser,'surviving loser opens next hand');check(snap(g).results.length===1,'history survives re-roll');}check(starters.size===3,'all seats can start');
const stale=state('pokemon-liars-dice'),st=stale.data as any;const caller=stale.currentPlayerId!;act(stale,caller,{type:'call',count:1,face:0});const captured={...st.call};const next=stale.currentPlayerId!;act(stale,next,{type:'call',count:2,face:0});const lives={...st.lives};check(!!MODULES['pokemon-liars-dice'].action(stale,stale.currentPlayerId!,{type:'open',expectedHand:st.hand,expectedCall:captured},c),'stale displayed call rejected even with fresh transport turn');check(JSON.stringify(st.lives)===JSON.stringify(lives),'stale challenge never damages anyone');
for(const p of ALL_POKEMON){const t=cardTier(p.id),value=cardValue(p.id);check(value>=t.min&&value<=t.max,'every card lies in advertised interval');}
for(const tool of Object.keys(AUCTION_TOOLS)){const g=state('pokemon-auction'),d=g.data as any;check(g.phase==='purchase'&&snap(g).publicInfo.length===0,'separate purchase');check(act(g,'a',{type:'buy-tool',tool})===null,'buy tool');const item=d.inventory.a[0];check(!!act(g,'a',{type:'use-tool',itemId:item.id,axis:'row',index:0,tier:'top'}),'no use in purchase');ready(g);check(g.phase==='intel','purchase leads to use');check(!!act(g,'a',{type:'buy-tool',tool:'scan'}),'no purchase in use');check(act(g,'a',{type:'use-tool',itemId:item.id,axis:'row',index:0,tier:'top'})===null,'all seven tools work');const other=snap(g,'b');check(other.events[0].playerId==='a'&&other.events[0].tool===tool&&other.myTools.length===0&&!('text' in other.events[0]),'public usage without private result');ready(g);act(g,'a',{type:'bid',amount:10});check(snap(g,'b').bidHistory.length===0,'no disclosure before everyone locks');act(g,'b',{type:'bid',amount:10});act(g,'c',{type:'bid',amount:10});check(snap(g,'b').bidHistory[0].bids.a===10,'public round prices after locking');check(snap(g).knownFloor<=d.box.reduce((sum:number,id:number|null)=>sum+(id?cardValue(id):0),0),'floor never above actual value');}
check(knownValueFloor([{tool:'tier',tier:'valuable',count:3,text:'',bidRound:1}])>=1200,'tier count lower bound');
check(knownValueFloor([{tool:'wide',axis:'row',index:0,sum:1000,text:'',bidRound:1},{tool:'wide',axis:'row',index:0,sum:1000,text:'',bidRound:1}])===1000,'identical scopes do not double count');
const deck=adventureDeck();for(let n=1;n<=10;n++)check(deck.filter(v=>v===n).length===3,'three copies per number');check(deck.length===42,'six tools each twice');
const passing=state('pokemon-push-your-luck'),pd=passing.data as any;pd.players.a.hand=[4];act(passing,'a',{type:'stop'});check(passing.points.a===0&&pd.players.a.status==='stopped','passing does not bank');act(passing,'b',{type:'draw'});act(passing,'c',{type:'stop'});check(passing.currentPlayerId==='a'&&pd.players.a.status==='active','pass returns on next turn');
const closing=state('pokemon-push-your-luck');(closing.data as any).players.a.hand=[4];for(const id of c.online)act(closing,id,{type:'stop'});check(closing.phase==='roundResult'&&closing.points.a===4,'all consecutive passes settle');
const delivery=state('pokemon-push-your-luck'),dd=delivery.data as any;dd.deck=['delivery',1,2,3,9];dd.players.b.status='stopped';act(delivery,'a',{type:'draw'});check(dd.players.b.hand[0]===1&&dd.players.c.hand[0]===2&&dd.players.a.hand[0]===3,'delivery order next seat then owner, including stopped');check(delivery.currentPlayerId==='b','forced queue returns to normal next turn');
const nested=state('pokemon-push-your-luck'),nd=nested.data as any;nd.deck=['delivery','peek',1,2,3,4];act(nested,'a',{type:'draw'});check(nested.phase==='peek'&&nested.currentPlayerId==='b'&&snap(nested,'a').peek===null,'forced peek remains private');act(nested,'b',{type:'take-peek'});check(nd.players.b.hand[0]===1&&nd.players.c.hand[0]===2&&nd.players.a.hand[0]===3,'nested special completes before queue resumes');
const theft=state('pokemon-push-your-luck'),tf=theft.data as any;tf.deck=['discard',1];tf.players.a.hand=[8];tf.players.b.hand=[2,3];tf.players.c.hand=[7];act(theft,'a',{type:'draw'});check(tf.players.a.hand.join(',')==='8'&&tf.players.b.hand.length===1&&tf.players.c.hand.length===0&&tf.discard.length===3,'theft discards, never gives owner cards');
const double=state('pokemon-push-your-luck'),db=double.data as any;db.deck=['double',1];act(double,'a',{type:'draw'});check(db.players.a.hand.join(',')==='4,7','double gets four then seven');
const bust=state('pokemon-push-your-luck'),bd=bust.data as any;bd.deck=['double',1];bd.players.a.hand=[4];act(bust,'a',{type:'draw'});check(bd.players.a.status==='bust'&&bd.players.a.hand.length===0,'double duplicate bust prevents second award');
const trap=state('surround-meloetta'),td=trap.data as any;td.position={q:3,r:0};td.obstacles=[{q:4,r:0},{q:4,r:-1},{q:3,r:1}];td.dancing=true;td.countdown=0;td.breakUsed=true;const placed={q:-4,r:0};const r=previewTrap(td,placed);check(r.breakUsed&&r.outcome==='break','proactive kick even with alternative escape and prior transformation used');check(HEX_DIRECTIONS.some(v=>r.position.q===td.position.q+v.q&&r.position.r===td.position.r+v.r),'only adjacent break');const old=escapePath(td.position,[...td.obstacles,placed]),fresh=escapePath(r.position,r.obstacles);check(fresh!.length+1<old!.length,'kick selects strictly shorter escape');act(trap,trap.currentPlayerId!,{type:'block',...placed});check(!td.dancing&&!td.breakUsed&&td.countdown>=2,'restores form and re-arms future transformation');
console.log(`PLAYTEST OCT6 PASS: ${checks} checks`);
