import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {rocketSecret} from '../src/server/batch/rocket';
import {rocketReportText,type RocketReport} from '../src/lib/rocketReport';
import {RocketMatchReview} from '../src/components/games/RocketReview';
import {SECOND_DEFAULTS} from '../src/lib/secondTypes';
import type {BatchState,BatchContext} from '../src/server/batch/core';
let checks=0,seed=125;const check=(v:unknown,l:string)=>{assert.ok(v,l);checks++;};const c:BatchContext={now:100,random:()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;},online:['a','b','c'],hostId:'a',settings:{...SECOND_DEFAULTS,rocketCycles:1},ms:{turn:120000,wallTurn:120000,feedback:1500,memoryReveal:2000,question:120000,questionReveal:3000,prepare:3000,bombRound:180000,offline:30000,relayMin:20000,relayMax:40000,driveSecond:1000}};
const g:BatchState={kind:'rocket-secret',timers:[],matchId:'m',roundId:'r',turnId:'t',phase:'',round:1,totalRounds:1,deadline:null,currentPlayerId:null,participants:['a','b','c'],points:{a:0,b:0,c:0},ranks:null,gains:null,notice:null,pausedAt:null,onlineIds:[],processed:new Map(),awarded:false,completedRounds:0,data:null};rocketSecret.create(g,c);
const act=(id:string,a:Record<string,unknown>)=>rocketSecret.action(g,id,a,c),snap=(id:string)=>rocketSecret.snapshot(g,id,c) as any;
for(let question=1;question<=3;question++){const d=g.data as any;const answer=[...d.answer],wrong=[answer[1],answer[0],answer[2],answer[3]],guessers=g.participants.filter(id=>id!==d.sender);check(!('revealedHistory' in snap(guessers[0])),'current history hidden before reveal');act(d.sender,{type:'transmit',texts:['花香','海浪','天空','伙伴']});for(const id of guessers)act(id,{type:'guess-sequence',picks:wrong});check(g.phase==='transmit'&&d.attempt===2,'failed first attempt continues');check(!('revealedHistory' in snap('spectator'))&&snap('spectator').reports.length===0,'active question never broadcasts report history');act(d.sender,{type:'transmit',texts:['芬芳','潮汐','晴空','友谊']});act(guessers[0],{type:'guess-sequence',picks:answer});rocketSecret.advance(g,{...c,now:g.deadline!});check(g.phase==='discussion','timeout resolves remaining guesser');const s=snap('spectator'),r=s.reports.at(-1) as RocketReport;check(r.history[guessers[0]].length===2&&r.history[guessers[1]].length===1,'complete history includes earlier guesses and missing last submission');check(s.revealedHistory[guessers[0]][0].picks.join()===wrong.join(),'public history after reveal');s.reports.at(-1).answer[0]=999;s.revealedHistory[guessers[0]][0].picks[0]=999;check(d.reports.at(-1).answer[0]===answer[0]&&d.history[guessers[0]][0].picks[0]!==999,'report snapshots immutable');act('a',{type:'next'});}
check(g.phase==='final','final retains reports');const reports=snap('spectator').reports as RocketReport[];check(reports.length===3&&reports.every(r=>r.clues.length===2),'all questions archived');const text=rocketReportText('TEST',reports,id=>({a:'发报甲',b:'猜测乙',c:'猜测丙'})[id]??id,id=>`宝可梦${id}`);check(text.includes('房间：TEST')&&text.includes('第 3 题')&&text.includes('第 1 次发报')&&text.includes('第 2 次发报'),'portable report chronology');check(text.includes('未提交（超时或断线）')&&text.includes('完全正确')&&text.includes('位置正确 2/4')&&text.includes('战报累计得分'),'missing submissions, correctness and scoring included');const view={code:'TEST',players:[{id:'a',nickname:'发报甲'},{id:'b',nickname:'猜测乙'},{id:'c',nickname:'猜测丙'}]} as any;const html=renderToStaticMarkup(React.createElement(RocketMatchReview,{view,reports}));check(!/<details[^>]*\bopen\b/.test(html),'all final reviews collapsed by default');check(html.includes('复制整场战报')&&html.includes('展开第 1 次所有人的猜测'),'final export and per-attempt controls');
console.log(`ROCKET REVIEW PASS: ${checks} checks`);
