import assert from 'node:assert/strict';
import {MODULES} from '../src/server/batch';
import {SECOND_DEFAULTS,type SecondGameType} from '../src/lib/secondTypes';
import type {BatchState,BatchContext} from '../src/server/batch/core';
import {auctionWinner,cardValue,makeBox} from '../src/server/batch/auction';
import {legalCall,countDice} from '../src/server/batch/dice';
import {graphemes,validateClues} from '../src/server/batch/rocket';
import {adventureDeck,legalTrades} from '../src/lib/greed';
import {hexCells,hexDistance,escapePath,previewTrap} from '../src/lib/meloetta';
let checks=0,seed=9823;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
const c:BatchContext={now:1000,random,online:['a','b','c'],hostId:'a',settings:{...SECOND_DEFAULTS,rocketCycles:1,auctionBoxes:1,diceMatches:1,trapRounds:1,luckRounds:1},ms:{turn:20000,wallTurn:30000,feedback:1500,memoryReveal:2000,question:15000,questionReveal:3000,prepare:3000,bombRound:180000,offline:30000,relayMin:20000,relayMax:40000,driveSecond:1000}};
function check(v:unknown,label:string){assert.ok(v,label);checks++;}
function state(kind:SecondGameType){const g:BatchState={kind,timers:[],matchId:'m',roundId:'r',turnId:'t',phase:'',round:1,totalRounds:1,deadline:null,currentPlayerId:null,participants:['a','b','c'],points:{a:0,b:0,c:0},ranks:null,gains:null,notice:null,pausedAt:null,onlineIds:[],processed:new Map(),awarded:false,completedRounds:0,data:null};MODULES[kind].create(g,c);return g;}
const act=(g:BatchState,id:string,a:Record<string,unknown>)=>MODULES[g.kind].action(g,id,a,c);
const snap=(g:BatchState,id:string)=>MODULES[g.kind].snapshot(g,id,c) as any;
const advance=(g:BatchState)=>MODULES[g.kind].advance(g,{...c,now:g.deadline!});
check(graphemes('👨‍👩‍👧‍👦花')===2,'Unicode visible characters');check(!!validateClues(['一','二','三','123'],[25]),'number coding rejected');
const rocket=state('rocket-secret'),rd=rocket.data as any;check(rocket.totalRounds===3,'custom cycle times participants');check(!('answer' in snap(rocket,'c'))&&!('excluded' in snap(rocket,'c')),'interceptor receives no secret answer/exclusions');check(snap(rocket,'b').excluded.every((id:number)=>!rd.answer.includes(id)),'exclusions never remove answer');
check(act(rocket,'a',{type:'draft',texts:['花香','海浪','天空','伙伴']})===null,'valid saved draft');advance(rocket);check(rocket.phase==='decode'&&snap(rocket,'c').clues[0].texts.length===4,'deadline sends saved draft');
check(act(rocket,'b',{type:'guess-sequence',picks:rd.answer})===null,'contact guess locks');check(snap(rocket,'c').myGuess===null&&!snap(rocket,'c').result,'other guess is private before all finish');act(rocket,'c',{type:'guess-sequence',picks:rd.answer});check(rocket.phase==='discussion'&&rocket.deadline===null&&rocket.points.a===1&&rocket.points.b===1&&rocket.points.c===2,'simultaneous success scoring and unlimited discussion');check(!!act(rocket,'b',{type:'next'}),'only host advances');act(rocket,'a',{type:'next'});check(rocket.round===2&&(rocket.data as any).sender==='b','sender rotates');
check(auctionWinner({a:150,b:100,c:0},1,random)==='a','150 percent exact boundary');check(auctionWinner({a:149,b:100},1,random)===null,'below boundary fails');check(auctionWinner({a:120,b:100},2,random)==='a','120 percent boundary');check(auctionWinner({a:1,b:0},1,random)==='a','single positive bid wins');check(auctionWinner({a:0,b:0},3,random)===null,'all zero unsold');check(['a','b'].includes(auctionWinner({a:10,b:10},3,random)!),'third round tie randomized');
for(let i=0;i<1000;i++){const box=makeBox(random);check(box.length===25&&box.filter(x=>x!==null).length>=8&&box.filter(x=>x!==null).length<=15,'box size distribution bounds');}
const auction=state('pokemon-auction'),ad=auction.data as any;check(!('box' in snap(auction,'a')),'box hidden before reveal');act(auction,'a',{type:'buy-tool',tool:'detector'});check(auction.points.a===9900&&MODULES['pokemon-auction'].publicPoints!(auction,'b').a===10000,'private purchase does not leak through public cash');check(snap(auction,'b').myTools.length===0,'private tool result');act(auction,'a',{type:'buy-tool',tool:'focus'});check(!!act(auction,'a',{type:'buy-tool',tool:'scan',index:0}),'two tool maximum');for(const id of c.online)act(auction,id,{type:'ready'});act(auction,'a',{type:'bid',amount:1});check(snap(auction,'b').myBid===null&&!snap(auction,'b').result,'sealed bids');act(auction,'b',{type:'bid',amount:0});act(auction,'c',{type:'bid',amount:0});check(auction.phase==='boxResult'&&ad.result.value===ad.box.reduce((n:number,id:number|null)=>n+(id===null?0:cardValue(id)),0),'revealed sale uses actual BST value');check(auction.points.a===9750+ad.result.value-1,'tools and automatic resale settle exactly');advance(auction);check(auction.phase==='final','custom one box ends');
const abort=state('pokemon-auction');act(abort,'a',{type:'buy-tool',tool:'focus'});MODULES['pokemon-auction'].abort!(abort,c);check(abort.points.a===10000,'system abort refunds unfinished box tool fees');
check(!legalCall({count:1,face:5},null,15),'wild face cannot be called');check(legalCall({count:2,face:0},{count:1,face:4},15),'higher count permits any ordinary face');check(!legalCall({count:16,face:0},null,15),'count limited to total dice');check(countDice({a:[0,5,1,5,2]},0)===3,'wild contributes to called face');
const dice=state('pokemon-liars-dice');check(snap(dice,'a').myDice.length===5&&!('dice' in snap(dice,'a'))&&snap(dice,'spectator').myDice.length===0,'dice private per player');let guard=0;while(dice.phase!=='final'&&guard++<100){if(dice.phase==='turn'){const dd=dice.data as any;act(dice,dice.currentPlayerId!,dd.call?{type:'open'}:{type:'call',count:dd.alive.length*5,face:0});}else advance(dice);}check(dice.phase==='final'&&dice.completedRounds===1&&Object.values(dice.points).sort().join(',')==='0,1,2','three lives elimination and N-rank scoring');
check(adventureDeck().length===46,'46 card deck');check(hexCells().length===91,'radius five hex board');
const luck=state('pokemon-push-your-luck'),ld=luck.data as any;ld.deck=['peek','peek',7,7];act(luck,'a',{type:'draw'});check(luck.phase==='peek'&&snap(luck,'a').peek==='peek'&&snap(luck,'b').peek===null,'peek top card only owner');act(luck,'a',{type:'take-peek'});check(luck.phase==='peek'&&luck.currentPlayerId==='a'&&snap(luck,'a').peek===7,'chained special does not interleave');act(luck,'a',{type:'take-peek'});check(ld.players.a.hand[0]===7&&luck.currentPlayerId==='b','take consumes exactly visible top');ld.players.b.hand=[7];ld.players.b.shield=true;act(luck,'b',{type:'draw'});check(ld.players.b.hand[0]===7&&!ld.players.b.shield&&ld.players.b.status==='stopped'&&luck.phase==='roundResult','last duplicate shield resolves before empty deck banks everyone');check(luck.points.a===7&&luck.points.b===7,'remaining active players bank on empty deck');
const trades=legalTrades({a:{hand:[1,2],shield:true,status:'active',banked:0},b:{hand:[2,3],shield:false,status:'active',banked:0},c:{hand:[4],shield:false,status:'stopped',banked:4}},'a');check(trades.every(t=>t.target==='b'&&!([1,2].filter(n=>n!==t.own).includes(t.other))&&!([2,3].filter(n=>n!==t.other).includes(t.own))),'exchange rejects duplicate hands and stopped targets');
for(let i=0;i<1000;i++){const g=state('surround-meloetta'),d=g.data as any;check(d.obstacles.length===8&&!!escapePath(d.position,d.obstacles)&&d.countdown>=2&&d.countdown<=4,'initial trap always reachable with eight obstacles');const legal=hexCells().find(h=>hexDistance(h)>0&&!d.obstacles.some((o:any)=>o.q===h.q&&o.r===h.r))!;const preview=previewTrap(d,legal);act(g,'a',{type:'block',...legal});check(JSON.stringify((g.data as any).position)===JSON.stringify(preview.position),'local preview equals server result');}
const idle=state('surround-meloetta');advance(idle);advance(idle);advance(idle);check(idle.phase==='idle'&&idle.deadline!==null,'inactive full round waits thirty seconds');act(idle,'b',{type:'resume'});check(idle.phase==='turn'&&idle.currentPlayerId==='b','participant resumes inactive round');advance(idle);advance(idle);advance(idle);advance(idle);check(idle.phase==='final'&&idle.completedRounds===0,'inactive unfinished round gives no raw points');
console.log(`THIRD PASS: ${checks} checks`);
