import assert from 'node:assert/strict';
import {MODULES} from '../src/server/batch';
import {SECOND_DEFAULTS,type SecondGameType} from '../src/lib/secondTypes';
import type {BatchState,BatchContext} from '../src/server/batch/core';
import {auctionWinner,cardValue,makeBox} from '../src/server/batch/auction';
import {legalCall,countDice} from '../src/server/batch/dice';
import {graphemes,validateClues} from '../src/server/batch/rocket';
import {adventureDeck,legalTrades} from '../src/lib/greed';
import {hexCells,hexDistance,escapePath,previewTrap} from '../src/lib/meloetta';
let checks=0,seed=9823;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
const c:BatchContext={now:1000,random,online:['a','b','c'],hostId:'a',settings:{...SECOND_DEFAULTS,rocketCycles:1,auctionBoxes:1,diceMatches:1,trapRounds:1,luckRounds:1},ms:{turn:120000,wallTurn:120000,feedback:1500,memoryReveal:2000,question:120000,questionReveal:3000,prepare:3000,bombRound:180000,offline:30000,relayMin:20000,relayMax:40000,driveSecond:1000}};
function check(v:unknown,label:string){assert.ok(v,label);checks++;}
function state(kind:SecondGameType){const g:BatchState={kind,timers:[],matchId:'m',roundId:'r',turnId:'t',phase:'',round:1,totalRounds:1,deadline:null,currentPlayerId:null,participants:['a','b','c'],points:{a:0,b:0,c:0},ranks:null,gains:null,notice:null,pausedAt:null,onlineIds:[],processed:new Map(),awarded:false,completedRounds:0,data:null};MODULES[kind].create(g,c);return g;}
const act=(g:BatchState,id:string,a:Record<string,unknown>)=>MODULES[g.kind].action(g,id,a.type==='open'?{...a,expectedHand:(g.data as any).hand,expectedCall:(g.data as any).call}:a,c);
const readyAll=(g:BatchState)=>{for(const id of c.online)act(g,id,{type:'ready'});};
const snap=(g:BatchState,id:string)=>MODULES[g.kind].snapshot(g,id,c) as any;
const advance=(g:BatchState)=>MODULES[g.kind].advance(g,{...c,now:g.deadline!});
check(graphemes('👨‍👩‍👧‍👦花')===2,'Unicode visible characters');check(!!validateClues(['一','二','三','123'],[25]),'number coding rejected');
const rocket=state('rocket-secret'),rd=rocket.data as any;check(rocket.totalRounds===3,'custom cycle times participants');check(!('answer' in snap(rocket,'c'))&&!('excluded' in snap(rocket,'c')),'interceptor receives no secret answer/exclusions');check(snap(rocket,'b').excluded.every((id:number)=>!rd.answer.includes(id)),'exclusions never remove answer');
check(act(rocket,'a',{type:'draft',texts:['花香','海浪','天空','伙伴']})===null,'valid saved draft');advance(rocket);check(rocket.phase==='decode'&&snap(rocket,'c').clues[0].texts.length===4,'deadline sends saved draft');
check(act(rocket,'b',{type:'guess-sequence',picks:rd.answer})===null,'contact guess locks');check(snap(rocket,'c').myGuess===null&&!snap(rocket,'c').result,'other guess is private before all finish');act(rocket,'c',{type:'guess-sequence',picks:rd.answer});check(rocket.phase==='discussion'&&rocket.deadline===null&&rocket.points.a===1&&rocket.points.b===1&&rocket.points.c===2,'simultaneous success scoring and unlimited discussion');check(!!act(rocket,'b',{type:'next'}),'only host advances');act(rocket,'a',{type:'next'});check(rocket.round===2&&(rocket.data as any).sender==='b','sender rotates');
check(auctionWinner({a:150,b:100,c:0},1,random)==='a','150 percent exact boundary');check(auctionWinner({a:149,b:100},1,random)===null,'below boundary fails');check(auctionWinner({a:120,b:100},2,random)==='a','120 percent boundary');check(auctionWinner({a:1,b:0},1,random)==='a','single positive bid wins');check(auctionWinner({a:0,b:0},3,random)===null,'all zero unsold');check(['a','b'].includes(auctionWinner({a:10,b:10},3,random)!),'third round tie randomized');
for(let i=0;i<1000;i++){const box=makeBox(random);check(box.length===25&&box.filter(x=>x!==null).length>=8&&box.filter(x=>x!==null).length<=15,'box size distribution bounds');}
const auction=state('pokemon-auction'),ad=auction.data as any;check(!('box' in snap(auction,'a')),'box hidden before reveal');act(auction,'a',{type:'buy-tool',tool:'detector'});check(auction.points.a===9900&&MODULES['pokemon-auction'].publicPoints!(auction,'b').a===10000,'private purchase does not leak through public cash');check(snap(auction,'b').myInventory.length===0,'private backpack');act(auction,'a',{type:'buy-tool',tool:'focus'});check(!!act(auction,'a',{type:'buy-tool',tool:'scan'}),'two purchases maximum');check(!!act(auction,'a',{type:'use-tool',itemId:ad.inventory.a[0].id}),'cannot use during purchase');readyAll(auction);act(auction,'a',{type:'use-tool',itemId:ad.inventory.a[0].id});check(snap(auction,'a').myTools[0].text.includes('张'),'backpack provides private result');check(!!act(auction,'a',{type:'use-tool',itemId:ad.inventory.a[0].id}),'one use per round');readyAll(auction);act(auction,'a',{type:'bid',amount:1});check(snap(auction,'b').myBid===null&&!snap(auction,'b').result,'sealed bids');act(auction,'b',{type:'bid',amount:0});act(auction,'c',{type:'bid',amount:0});check(auction.phase==='boxResult'&&ad.result.value===ad.box.reduce((n:number,id:number|null)=>n+(id===null?0:cardValue(id)),0),'actual BST sale');check(auction.points.a===9750+ad.result.value-1,'fees and resale exact');advance(auction);check(auction.phase==='final','custom box ends');
const abort=state('pokemon-auction');act(abort,'a',{type:'buy-tool',tool:'focus'});MODULES['pokemon-auction'].abort!(abort,c);check(abort.points.a===10000,'system abort refunds unfinished box tool fees');
check(!legalCall({count:1,face:5},null,15),'wild face cannot be called');check(legalCall({count:2,face:0},{count:1,face:4},15),'higher count permits any ordinary face');check(!legalCall({count:16,face:0},null,15),'count limited to total dice');check(countDice({a:[0,5,1,5,2]},0)===3,'wild contributes to called face');
const dice=state('pokemon-liars-dice');check(snap(dice,'a').myDice.length===5&&!('dice' in snap(dice,'a'))&&snap(dice,'spectator').myDice.length===0,'dice private per player');let guard=0;while(dice.phase!=='final'&&guard++<100){if(dice.phase==='turn'){const dd=dice.data as any;act(dice,dice.currentPlayerId!,dd.call?{type:'open'}:{type:'call',count:dd.alive.length*5,face:0});}else advance(dice);}check(dice.phase==='final'&&dice.completedRounds===1&&Object.values(dice.points).sort().join(',')==='0,1,2','three lives elimination and N-rank scoring');
check(adventureDeck().length===42,'42 card deck');check(hexCells().length===91,'radius five hex board');
const luck=state('pokemon-push-your-luck'),ld=luck.data as any;ld.deck=['peek','peek',7,7];act(luck,'a',{type:'draw'});check(luck.phase==='peek'&&snap(luck,'a').peek==='peek'&&snap(luck,'b').peek===null,'peek top card only owner');act(luck,'a',{type:'take-peek'});check(luck.phase==='peek'&&luck.currentPlayerId==='a'&&snap(luck,'a').peek===7,'chained special does not interleave');act(luck,'a',{type:'take-peek'});check(ld.players.a.hand[0]===7&&luck.currentPlayerId==='b','take consumes exactly visible top');ld.players.b.hand=[7];ld.players.b.shield=true;act(luck,'b',{type:'draw'});check(ld.players.b.hand[0]===7&&!ld.players.b.shield&&luck.phase==='roundResult','last duplicate shield resolves before empty deck banks everyone');check(luck.points.a===7&&luck.points.b===7,'remaining active players bank on empty deck');
const trades=legalTrades({a:{hand:[1,2],shield:true,status:'active',banked:0},b:{hand:[2,3],shield:false,status:'active',banked:0},c:{hand:[4],shield:false,status:'stopped',banked:4}},'a');check(trades.every(t=>t.target!=='a'&&!([1,2].filter(n=>n!==t.own).includes(t.other))&&!((t.target==='b'?[2,3]:[4]).filter(n=>n!==t.other).includes(t.own))),'exchange rejects duplicates; temporarily stopped players remain targets');
for(let i=0;i<1000;i++){const g=state('surround-meloetta'),d=g.data as any;check(d.obstacles.length===8&&!!escapePath(d.position,d.obstacles)&&d.countdown>=2&&d.countdown<=4,'initial trap always reachable with eight obstacles');const legal=hexCells().find(h=>hexDistance(h)>0&&!d.obstacles.some((o:any)=>o.q===h.q&&o.r===h.r))!;const preview=previewTrap(d,legal);act(g,'a',{type:'block',...legal});check(JSON.stringify((g.data as any).position)===JSON.stringify(preview.position),'local preview equals server result');}
const timedTrap=state('surround-meloetta'),td=timedTrap.data as any,nextCell=escapePath(td.position,td.obstacles)![1];advance(timedTrap);check(td.last.placed.q===nextCell.q&&td.last.placed.r===nextCell.r,'timeout blocks next escape cell and executes action');check(timedTrap.phase!=='idle','timeouts no longer skip turns or idle');
const danceTrap=state('surround-meloetta'),danceData=danceTrap.data as any;danceData.countdown=1;const far=hexCells().find(h=>hexDistance(h)===5&&!danceData.obstacles.some((p:any)=>p.q===h.q&&p.r===h.r))!;act(danceTrap,'a',{type:'block',...far});check(danceData.dancing&&danceData.countdown===0,'unspent dance persists after movement');
const stages=state('pokemon-auction'),sd=stages.data as any;readyAll(stages);check(sd.publicInfo.length===1&&sd.publicInfo[0].bidRound===1,'first round public hint');for(let round=1;round<=3;round++){check(stages.phase==='intel'&&sd.bidRound===round,'every bidding round has intel stage');check(sd.publicInfo.length===(round===3?2:1),'public hint only first and third rounds');for(const id of c.online)act(stages,id,{type:'ready'});check(stages.phase==='bid','all finish intelligence before sealed bids');for(const id of c.online)act(stages,id,{type:'bid',amount:1});}check(stages.phase==='boxResult','third identical bid resolves sale');
const carry=state('pokemon-auction'),cd=carry.data as any;carry.totalRounds=2;cd.box=[...Array(8).fill(1),...Array(17).fill(null)];act(carry,'a',{type:'buy-tool',tool:'wide'});const storedId=cd.inventory.a[0].id;readyAll(carry);readyAll(carry);for(const id of c.online)act(carry,id,{type:'bid',amount:id==='a'?1:0});advance(carry);const carried=carry.data as any;check(carry.round===2&&carried.inventory.a[0].id===storedId,'unused inventory carries to next box');act(carry,'a',{type:'buy-tool',tool:'focus'});readyAll(carry);act(carry,'a',{type:'use-tool',itemId:storedId,axis:'row',index:0});MODULES['pokemon-auction'].abort!(carry,c);check(carry.points.a===carried.boxStart.a&&carried.inventory.a[0].id===storedId&&carried.inventory.a.length===1,'system abort refunds current purchases and restores consumed carried tool');

const hintTools=new Set<string>();
for(let sample=0;sample<100;sample++){
 const g=state('pokemon-auction'),d=g.data as any;readyAll(g);const info=d.publicInfo[0];hintTools.add(info.tool);check(JSON.stringify(snap(g,'a').publicInfo)===JSON.stringify(snap(g,'b').publicInfo),'identical shared hint');d.inventory.a.push({id:'test',tool:info.tool});check(act(g,'a',{type:'use-tool',itemId:'test',axis:info.axis,index:info.index,tier:info.tier})===null,'shared hint scope valid');check(d.tools.a[0].text===info.text,'public and tool effects match');check(g.deadline===c.now+120000,'full 120 seconds');
}
check(hintTools.size===7,'random hints cover seven tools');
const locked=state('pokemon-auction'),lockedData=locked.data as any;
act(locked,'a',{type:'buy-tool',tool:'scan'});const scanId=lockedData.inventory.a[0].id;readyAll(locked);
check(!!act(locked,'a',{type:'use-tool',itemId:scanId,index:26})&&lockedData.inventory.a.length===1&&!lockedData.usedThisRound.length,'invalid scope neither consumes item nor use budget');
act(locked,'a',{type:'ready'});check(locked.phase==='intel','first ready waits for other players');
check(!!act(locked,'a',{type:'use-tool',itemId:scanId,index:0}),'ready player cannot change intelligence');
act(locked,'b',{type:'ready'});act(locked,'c',{type:'ready'});
check(locked.phase==='bid'&&locked.deadline===c.now+120000,'unified sealed bids get 120 seconds');
check(!!act(locked,'a',{type:'use-tool',itemId:scanId,index:0})&&lockedData.inventory.a.length===1,'no tool effects while another player could already have locked a bid');
const nextMatch=state('pokemon-auction');check((nextMatch.data as any).inventory.a.length===0,'new match clears backpack');


console.log(`THIRD PASS: ${checks} checks`);